/*
 * DialigPatientPaid.java
 *
 * Created on 12 มิถุนายน 2547, 16:09 น.
 */
package com.hosv3.gui.dialog;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.*;

import com.hosv3.utility.*;
import com.hosv3.control.*;
import com.hosv3.utility.connection.*;
import com.hosv3.object.*;

import com.hospital_os.utility.TaBleModel;
import com.hospital_os.object.*;
import com.hospital_os.utility.ComboboxModel;
import com.hospital_os.utility.Gutil;
import com.hosv3.utility.Constant;

/**
 *
 * @author  tong
 *  ผู้ป่วยรับชำระเงิน
 */
public class DialogPatientPaid extends javax.swing.JDialog implements UpdateStatus
{
    HosControl theHC;
    HosObject theHO;
    UpdateStatus theUS;
    JFrame jf;
    
    BillingControl theBillingControl;
    VisitControl theVisitControl;
    LookupControl theLookupControl;
    Visit theVisit;
    Patient thePatient;
    Vector vBillingInvoiceSubgroup;
    Billing theBilling;
    String receiptObjectId = "";
    public static boolean actionCommand = false;
    DefaultTableCellRenderer rendererRight = new DefaultTableCellRenderer();
    String col[] = {"รายการ","สิทธิ","สิทธิชำระ","ผู้ป่วยชำระ"};
    
    /**add code by noom*/
    public DialogPatientPaid(HosControl hc,UpdateStatus theUS
    ,Billing billing,Visit visit) {
        super(theUS.getJFrame(),true);
        initComponents();
        //setSize(500, 400);
        
	setControl(hc,theUS,billing,visit);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();//thekit.getScreenSize();
        setLocation((screenSize.width-getSize().width)/2, (screenSize.height-getSize().height)/2);
        setTitle(Constant.getTextBundle("การรับชำระเงิน"));
        setSize(1000, 800);      //pop
    }

    public void setControl(HosControl hc,UpdateStatus theUS
    ,Billing billing,Visit visit){
        theHC = hc;
        theHO = hc.theHO;
        theUS = hc.theUS;
        rendererRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        theBillingControl = theHC.theBillingControl;
        theVisitControl= theHC.theVisitControl;
        theLookupControl = theHC.theLookupControl;
        theVisit = visit;
        thePatient = theHC.theHO.thePatient;
        theBilling = billing;
        setObject(thePatient,theVisit);
        jButtonSave.setEnabled(true);
        doubleTextFieldPaid.setEnabled(true);
        setLanguage("");
        jTableListBilling.requestFocus();
        ComboboxModel.initComboBox(jComboBoxEmployee,theHC.theLookupControl.listReceiptModel());
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        defaultFont1 = new com.hospital_os.gui.font.DefaultFont();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabelDate = new javax.swing.JLabel();
        jLabelHN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelVN = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabelAgeValue = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jTextFieldPtName = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDX = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListBilling = new com.hosv3.gui.component.HJTableSort();
        jPanel8 = new javax.swing.JPanel();
        doubleTextFieldTotalAll = new com.hospital_os.utility.DoubleTextField();
        jLabelSum = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelPatientPay = new javax.swing.JLabel();
        jLabelPaid = new javax.swing.JLabel();
        jLabelPatientRemain = new javax.swing.JLabel();
        jTextFieldPatientRemain = new javax.swing.JTextField();
        jLabelReduce = new javax.swing.JLabel();
        jTextFieldReduce = new javax.swing.JTextField();
        doubleTextFieldPaid = new com.hospital_os.utility.DoubleTextField();
        doubleTextFieldPay = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxEmployee = new com.hosv3.gui.component.HosComboBox();
        jLabelPaidModel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonPreviewBilling = new javax.swing.JButton();
        jButtonPrintingBilling = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextThaiDx = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(808, 661));
        setPreferredSize(new java.awt.Dimension(808, 661));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabelDate.setFont(defaultFont1);
        jLabelDate.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel3.add(jLabelDate, gridBagConstraints);

        jLabelHN.setFont(defaultFont1);
        jLabelHN.setText("HN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jLabelHN, gridBagConstraints);

        jLabel5.setFont(defaultFont1);
        jLabel5.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabelVN.setFont(defaultFont1);
        jLabelVN.setText("VN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jLabelVN, gridBagConstraints);

        jLabel7.setFont(defaultFont1);
        jLabel7.setText("jLabel7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel1.setFont(defaultFont1);
        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabelAgeValue.setFont(defaultFont1);
        jLabelAgeValue.setText("jLabel8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel9.add(jLabelAgeValue, gridBagConstraints);

        jLabelAge.setFont(defaultFont1);
        jLabelAge.setText("Age");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel9.add(jLabelAge, gridBagConstraints);

        jTextFieldPtName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldPtName.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel9.add(jTextFieldPtName, gridBagConstraints);

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel9.add(jLabelName, gridBagConstraints);

        jLabel2.setFont(defaultFont1);
        jLabel2.setText("DX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 5);
        jPanel9.add(jLabel2, gridBagConstraints);

        jLabelDX.setFont(defaultFont1);
        jLabelDX.setText("jLabelDX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 5);
        jPanel9.add(jLabelDX, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel3.add(jPanel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 5);
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setMinimumSize(new java.awt.Dimension(135, 200));
        jPanel5.setPreferredSize(new java.awt.Dimension(135, 200));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportView(jTableListBilling);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jScrollPane2, gridBagConstraints);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        doubleTextFieldTotalAll.setBorder(null);
        doubleTextFieldTotalAll.setColumns(9);
        doubleTextFieldTotalAll.setEditable(false);
        doubleTextFieldTotalAll.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        doubleTextFieldTotalAll.setText("0");
        doubleTextFieldTotalAll.setFont(new java.awt.Font("MS Sans Serif", 0, 18)); // NOI18N
        doubleTextFieldTotalAll.setMinimumSize(new java.awt.Dimension(50, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel8.add(doubleTextFieldTotalAll, gridBagConstraints);

        jLabelSum.setFont(new java.awt.Font("MS Sans Serif", 0, 18)); // NOI18N
        jLabelSum.setText("TotalAll");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel8.add(jLabelSum, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel5.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabelPatientPay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPatientPay.setText("ชำระแล้ว");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 5, 1, 5);
        jPanel4.add(jLabelPatientPay, gridBagConstraints);

        jLabelPaid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPaid.setForeground(new java.awt.Color(0, 0, 255));
        jLabelPaid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaid.setText("รับชำระ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 5, 1, 5);
        jPanel4.add(jLabelPaid, gridBagConstraints);

        jLabelPatientRemain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPatientRemain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPatientRemain.setText("คงค้าง");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 5, 1, 5);
        jPanel4.add(jLabelPatientRemain, gridBagConstraints);

        jTextFieldPatientRemain.setEditable(false);
        jTextFieldPatientRemain.setFont(new java.awt.Font("MS Sans Serif", 0, 18)); // NOI18N
        jTextFieldPatientRemain.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPatientRemain.setText("0");
        jTextFieldPatientRemain.setBorder(null);
        jTextFieldPatientRemain.setEnabled(false);
        jTextFieldPatientRemain.setMaximumSize(new java.awt.Dimension(82, 32));
        jTextFieldPatientRemain.setMinimumSize(new java.awt.Dimension(82, 32));
        jTextFieldPatientRemain.setPreferredSize(new java.awt.Dimension(82, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel4.add(jTextFieldPatientRemain, gridBagConstraints);

        jLabelReduce.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelReduce.setText("ทอน");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 5, 1, 5);
        jPanel4.add(jLabelReduce, gridBagConstraints);

        jTextFieldReduce.setEditable(false);
        jTextFieldReduce.setFont(new java.awt.Font("MS Sans Serif", 0, 18)); // NOI18N
        jTextFieldReduce.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldReduce.setText("0");
        jTextFieldReduce.setBorder(null);
        jTextFieldReduce.setEnabled(false);
        jTextFieldReduce.setMinimumSize(new java.awt.Dimension(78, 32));
        jTextFieldReduce.setPreferredSize(new java.awt.Dimension(78, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel4.add(jTextFieldReduce, gridBagConstraints);

        doubleTextFieldPaid.setColumns(6);
        doubleTextFieldPaid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        doubleTextFieldPaid.setText("0");
        doubleTextFieldPaid.setFont(new java.awt.Font("MS Sans Serif", 0, 18)); // NOI18N
        doubleTextFieldPaid.setMaximumSize(new java.awt.Dimension(82, 32));
        doubleTextFieldPaid.setMinimumSize(new java.awt.Dimension(82, 32));
        doubleTextFieldPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleTextFieldPaidActionPerformed(evt);
            }
        });
        doubleTextFieldPaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                doubleTextFieldPaidFocusLost(evt);
            }
        });
        doubleTextFieldPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                doubleTextFieldPaidKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel4.add(doubleTextFieldPaid, gridBagConstraints);

        doubleTextFieldPay.setFont(new java.awt.Font("MS Sans Serif", 0, 18)); // NOI18N
        doubleTextFieldPay.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        doubleTextFieldPay.setText("0");
        doubleTextFieldPay.setBorder(null);
        doubleTextFieldPay.setEnabled(false);
        doubleTextFieldPay.setMaximumSize(new java.awt.Dimension(82, 32));
        doubleTextFieldPay.setMinimumSize(new java.awt.Dimension(82, 32));
        doubleTextFieldPay.setPreferredSize(new java.awt.Dimension(82, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel4.add(doubleTextFieldPay, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel6.add(jPanel4, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jComboBoxEmployee.setMinimumSize(new java.awt.Dimension(150, 21));
        jComboBoxEmployee.setPreferredSize(new java.awt.Dimension(150, 21));
        jComboBoxEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmployeeActionPerformed(evt);
            }
        });
        jComboBoxEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBoxEmployeeKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel1.add(jComboBoxEmployee, gridBagConstraints);

        jLabelPaidModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPaidModel.setText("วิธีการชำระเงิน");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        jPanel1.add(jLabelPaidModel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel6.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(jPanel6, gridBagConstraints);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel7.add(jButtonSave, gridBagConstraints);

        jButtonPreviewBilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hospital_os/images/preview24.gif"))); // NOI18N
        jButtonPreviewBilling.setToolTipText("PreviewBilling");
        jButtonPreviewBilling.setActionCommand("Printing");
        jButtonPreviewBilling.setMaximumSize(new java.awt.Dimension(26, 26));
        jButtonPreviewBilling.setMinimumSize(new java.awt.Dimension(26, 26));
        jButtonPreviewBilling.setPreferredSize(new java.awt.Dimension(26, 26));
        jButtonPreviewBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviewBillingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel7.add(jButtonPreviewBilling, gridBagConstraints);

        jButtonPrintingBilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hospital_os/images/print24.gif"))); // NOI18N
        jButtonPrintingBilling.setToolTipText("PrintingBilling");
        jButtonPrintingBilling.setActionCommand("Printing");
        jButtonPrintingBilling.setMaximumSize(new java.awt.Dimension(26, 26));
        jButtonPrintingBilling.setMinimumSize(new java.awt.Dimension(26, 26));
        jButtonPrintingBilling.setPreferredSize(new java.awt.Dimension(26, 26));
        jButtonPrintingBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintingBillingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel7.add(jButtonPrintingBilling, gridBagConstraints);

        jLabel4.setFont(defaultFont1);
        jLabel4.setText("Dx ในใบเสร็จ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 5);
        jPanel7.add(jLabel4, gridBagConstraints);

        jTextThaiDx.setFont(defaultFont1);
        jTextThaiDx.setMinimumSize(new java.awt.Dimension(120, 22));
        jTextThaiDx.setPreferredSize(new java.awt.Dimension(120, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 5);
        jPanel7.add(jTextThaiDx, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel7, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void doubleTextFieldPaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doubleTextFieldPaidKeyReleased
        if(doubleTextFieldPaid.getText().equals(""))
            doubleTextFieldPaid.setText("0");
        callMoneyPatient();
    }//GEN-LAST:event_doubleTextFieldPaidKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        theHO.thePrintReceipt = null;
    }//GEN-LAST:event_formWindowClosing
    private void jButtonPrintingBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintingBillingActionPerformed
        theHC.thePrintControl.printBilling(theVisit,theHO.thePrintReceipt,
                PrintControl.MODE_PRINT,jTextThaiDx.getText(),this);
    }//GEN-LAST:event_jButtonPrintingBillingActionPerformed
    private void doubleTextFieldPaidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_doubleTextFieldPaidFocusLost
                
    }//GEN-LAST:event_doubleTextFieldPaidFocusLost

    private void doubleTextFieldPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleTextFieldPaidActionPerformed
        jButtonSaveActionPerformed(null);
    }//GEN-LAST:event_doubleTextFieldPaidActionPerformed

     private void jButtonPreviewBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviewBillingActionPerformed
         //doubleTextFieldPaid.requestFocus();
        theHC.thePrintControl.printBilling(theVisit,theHO.thePrintReceipt, PrintControl.MODE_PREVIEW,jTextThaiDx.getText(),this);
    }//GEN-LAST:event_jButtonPreviewBillingActionPerformed

  private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
      boolean res = theBillingControl.patientPaidMoney(theBilling,vBillingInvoiceSubgroup
            ,doubleTextFieldPaid.getText(),Gutil.getGuiData(jComboBoxEmployee),this);
        if(!res)
            return;
        this.jButtonSave.setEnabled(false);
        this.doubleTextFieldPaid.setEnabled(false);
    }//GEN-LAST:event_jButtonSaveActionPerformed

  private void jComboBoxEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmployeeActionPerformed
      // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxEmployeeActionPerformed

  private void jComboBoxEmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxEmployeeKeyReleased
      // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxEmployeeKeyReleased
    private void callMoneyPatient()
    {
        String old_remain = jTextFieldPatientRemain.getText();
        String old_reduce = jTextFieldReduce.getText();
        try{
            double paid =  Double.parseDouble(doubleTextFieldPaid.getText());
            double totalpaid =  Double.parseDouble(doubleTextFieldPay.getText());
            double total =  Double.parseDouble(doubleTextFieldTotalAll.getText());
            double remain = total - (totalpaid + paid);
            double ret = 0;
            // ค่าใช้จ่าย 100 บาท ผู้ป่วยจ่าย 10 บาท คงค้าง 90 บาท ทอน 0 บาท
            // ค่าใช้จ่าย 100 บาท ผู้ป่วยจ่าย 110 บาท คงค้าง 0 บาท ทอน 10 บาท
            // ค่าใช้จ่าย 100 บาท ผู้ป่วยจ่ายครั้งที่แล้ว 50 บาท ผู้ป่วยจ่ายครั้งนี้ 10 บาท คงค้าง 40 บาท ทอน 0 บาท
            // ค่าใช้จ่าย 100 บาท ผู้ป่วยจ่ายครั้งที่แล้ว 50 บาท ผู้ป่วยจ่ายครั้งนี้ 60 บาท คงค้าง 4 บาท ทอน 10 บาท
            if(remain < 0) {
                ret = (paid + totalpaid)  - total;
                remain = 0;
            }
            ret = Math.ceil(ret);
            remain = Math.ceil(remain);
            jTextFieldPatientRemain.setText(String.valueOf(remain));
            jTextFieldReduce.setText(String.valueOf(ret));
        }
        catch(Exception e){
            Constant.println(e.getMessage());
            jTextFieldPatientRemain.setText(old_remain);
            jTextFieldReduce.setText(old_reduce);
        }
    }
               
 
 private void updateOG(Visit visit,Billing billing) 
 {
    theBilling = billing;
    theVisit = visit;
    vBillingInvoiceSubgroup = theBillingControl
        .readBillingInvoiceSubgroupByVisitIDBillingID(visit.getObjectId()
        ,billing.getObjectId());

    jLabelDX.setText(visit.doctor_dx);
    DxTemplate vDx_thai = theHC.theSetupControl.readDxTemplateByName(visit.doctor_dx);    
    if(vDx_thai == null)  
        jTextThaiDx.setText("");
    else    
        jTextThaiDx.setText(vDx_thai.thaidescription);

    setBillingInvoiceSubGroupV(vBillingInvoiceSubgroup);
 }
 
 /**
  *  หารายการ Billing Invoice Subgroup ตาม visit id
  *  ข้อมูลเข้า เป็น object ของ visit
  *  ข้อมูลออก เป็น Vector ของ object BillingInvoiceSubgroup
  */
 /**
  *  ให้ค่าลง Vector ของ BillingInvoiceSubgroup
  */
 
 private void setBillingInvoiceSubGroupV(Vector vc) 
 {
     TaBleModel tm;
     if(vc == null)
         tm = new TaBleModel(col,0);
     else{   
         tm = new TaBleModel(col,vc.size());
         BillingInvoiceSubgroup bis = null;
         Payment payment = null;
         String old_payment_id = null;
         for(int i=0,size=vc.size();i<size;i++) {
             bis = (BillingInvoiceSubgroup)vc.get(i);
             BillingGroupItem bgi = theLookupControl.readBillingGroupItemById(bis.billing_group_item_id);
             String plan =  "ไม่พบสิทธิการรักษา";
             
             if(!bis.payment_id.equals(old_payment_id)){
                 if(!bis.payment_id.equals("")){
                    payment = theVisitControl.listVisitPaymentByKeyID(bis.payment_id);
                 }
                 else
                     payment = (Payment)theHO.vVisitPayment.get(0);
             }
             old_payment_id = bis.payment_id;
             if(payment!=null)
                 plan = theLookupControl.readPlanString(payment.plan_kid);
             
             tm.setValueAt(bgi.description,i,0);
             tm.setValueAt(plan,i,1);
             tm.setValueAt(bis.payer_share_ceil,i,2);
             tm.setValueAt(Constant.dicimal(String.valueOf(bis.patient_share_ceil)),i,3);
         }
         double d = Float.parseFloat(Constant.dicimal(theBilling.patient_share));
         d = Math.ceil(d);
         doubleTextFieldTotalAll.setText(String.valueOf(d));
         //doubleTextFieldPay.setText(String.valueOf(d));
         doubleTextFieldPay.setText(Constant.dicimal(theBilling.paid));
         jTextFieldReduce.setText("0");
         jTextFieldPatientRemain.setText(Constant.dicimal(theBilling.remain));
     }
     jTableListBilling.setModel(tm);
     jTableListBilling.getColumnModel().getColumn(0).setPreferredWidth(400);
     jTableListBilling.getColumnModel().getColumn(1).setPreferredWidth(400);
     jTableListBilling.getColumnModel().getColumn(2).setPreferredWidth(100);
     jTableListBilling.getColumnModel().getColumn(2).setCellRenderer(rendererRight);
     jTableListBilling.getColumnModel().getColumn(3).setPreferredWidth(100);
     jTableListBilling.getColumnModel().getColumn(3).setCellRenderer(rendererRight);

 }
 
    private void setObject(Patient patient,Visit visit)
    { 
        String date_time = theHC.theLookupControl.getTextCurrentDateTime();
        jLabel5.setText(theLookupControl.getRenderTextHN(visit.hn));
        jLabel7.setText(theLookupControl.getRenderTextVN(visit.vn));
        String age = DateUtil.calculateAgeLong(patient.patient_birthday,theHO.date_time);
        jLabelAgeValue.setText(age);
        jLabel1.setText(DateUtil.getDateToString(DateUtil.getDateFromText(date_time),true));
        jTextFieldPtName.setText(theHC.theLookupControl.readPrefixString(patient.f_prefix_id) + " " + patient.patient_name + " " + patient.patient_last_name );
    }
 
     public void setLanguage(String name) 
     {
        GuiLang.setLanguage(jLabelPaidModel);
        GuiLang.setLanguage(jLabelSum);
        GuiLang.setLanguage(jLabelPaid);
        GuiLang.setLanguage(jLabelPatientPay);
        GuiLang.setLanguage(jLabelPatientRemain);
        GuiLang.setLanguage(jLabelAge);
        GuiLang.setLanguage(jLabelDate);
        GuiLang.setLanguage(jLabelHN);
        GuiLang.setLanguage(jLabelName);
        GuiLang.setLanguage(jButtonPrintingBilling);
        GuiLang.setLanguage(jButtonSave);
        GuiLang.setLanguage(jLabelReduce);
        GuiLang.setLanguage(jButtonPreviewBilling);
        GuiLang.setLanguage(jLabel2);
        GuiLang.setLanguage(jLabelVN);
        GuiLang.setLanguage(col);
        GuiLang.setLanguage(jLabel4);
        GuiLang.setLanguage(jLabelPaidModel);
     }
                          
 /*
  *รับค่า bill ครั้งใหม่เข้าไป และ visit ปัจจุบัน
 */
public static boolean showDialog(HosControl hc, UpdateStatus us,Billing billing,Visit visit)//, Office off)
{
    DialogPatientPaid dlg = new DialogPatientPaid(hc,us,billing,visit);//,off);
    dlg.updateOG(visit,billing);
    dlg.pack();
    dlg.doubleTextFieldPaid.requestFocus();
    dlg.setVisible(true);
    if(dlg.actionCommand)
        return true;
    return false;
}  
 
 public boolean confirmBox(String str, int status) {
     int i = JOptionPane.showConfirmDialog(this,str,"เตือน"
                ,JOptionPane.YES_NO_OPTION);
     return (i==JOptionPane.YES_OPTION);
 }
 
 public JFrame getJFrame() {
     return null;
 }
 
 public void setStatus(String str, int status) {
     str = Constant.getTextBundle(str);
     JOptionPane.showMessageDialog(this, str, "เตือน", JOptionPane.ERROR_MESSAGE); 
 }
 
// public void notifyBillingReceipt(String receiptId){
//     receiptObjectId = receiptId;
// }
 
 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.hospital_os.gui.font.DefaultFont defaultFont1;
    private com.hospital_os.utility.DoubleTextField doubleTextFieldPaid;
    private javax.swing.JTextField doubleTextFieldPay;
    private com.hospital_os.utility.DoubleTextField doubleTextFieldTotalAll;
    private javax.swing.JButton jButtonPreviewBilling;
    private javax.swing.JButton jButtonPrintingBilling;
    private javax.swing.JButton jButtonSave;
    private com.hosv3.gui.component.HosComboBox jComboBoxEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelAgeValue;
    private javax.swing.JLabel jLabelDX;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelHN;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPaid;
    private javax.swing.JLabel jLabelPaidModel;
    private javax.swing.JLabel jLabelPatientPay;
    private javax.swing.JLabel jLabelPatientRemain;
    private javax.swing.JLabel jLabelReduce;
    private javax.swing.JLabel jLabelSum;
    private javax.swing.JLabel jLabelVN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private com.hosv3.gui.component.HJTableSort jTableListBilling;
    private javax.swing.JTextField jTextFieldPatientRemain;
    private javax.swing.JLabel jTextFieldPtName;
    private javax.swing.JTextField jTextFieldReduce;
    private javax.swing.JTextField jTextThaiDx;
    // End of variables declaration//GEN-END:variables
    
    
}
