/*
 * DialogPrintOPD.java
 *
 * Created on 26 ธันวาคม 2546, 22:13 น.
 */
package com.hosv3.gui.dialog;
import java.awt.*;
import javax.swing.*;
import com.hosv3.utility.*;
import com.hosv3.control.*;
import com.hosv3.object.*;

/**
 *
 * @author  tong
 */
public class DialogPrintOPD extends javax.swing.JDialog {
    
    HosObject theHO;
    PrintControl thePrintControl;
    int valuePrint = PrintControl.MODE_PRINT;
    static boolean actionCommand;
    private JFrame jfrm;
    public DialogPrintOPD(Frame parent,int vp,HosControl hc) {
        super(parent, true);
        initComponents();
        valuePrint = vp;
        setLanguage("");
        jCheckBoxHeadName.setVisible(false);
       // jButtonPrintActionPerformed(null);
        jCheckBoxHead.setVisible(false);
        thePrintControl = hc.thePrintControl;
        theHO = hc.theHO;
        dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jCheckBoxHead = new javax.swing.JCheckBox();
        jCheckBoxDetail = new javax.swing.JCheckBox();
        jButtonPrint = new javax.swing.JButton();
        jCheckBoxHeadName = new javax.swing.JCheckBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("รูปแบบพิมพ์"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jCheckBoxHead.setSelected(true);
        jCheckBoxHead.setText("HEAD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        jPanel1.add(jCheckBoxHead, gridBagConstraints);

        jCheckBoxDetail.setSelected(true);
        jCheckBoxDetail.setText("DETAIL_OPD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(jCheckBoxDetail, gridBagConstraints);

        jButtonPrint.setText("PRINT");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 44);
        jPanel1.add(jButtonPrint, gridBagConstraints);

        jCheckBoxHeadName.setSelected(true);
        jCheckBoxHeadName.setText("SHOW_NAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 12, 0);
        jPanel1.add(jCheckBoxHeadName, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
         thePrintControl.printOPDCard(valuePrint,theHO.vVisitPayment);
         dispose();
    }//GEN-LAST:event_jButtonPrintActionPerformed
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    /**
     * @deprecated henbe unused
     * @param frm
     * @param valuePrint
     * @return
     */
    public static boolean showPanel(JFrame frm, int valuePrint){
        System.out.println("This function is not used");
        return false;
    }

    public static boolean showPanel(JFrame frm, int valuePrint,HosControl hc){
        DialogPrintOPD dlg = new DialogPrintOPD(frm,valuePrint,hc);
        dlg.setSize(300,150);
        dlg.setTitle("ยืนยันการพิมพ์");
      
        Toolkit thekit = dlg.getToolkit();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();//thekit.getScreenSize();
        dlg.setBounds((screenSize.width + dlg.getSize().width + 200 )/4,(screenSize.height + dlg.getSize().height + 50)/4, dlg.getSize().width,dlg.getSize().height);
        dlg.setVisible(true);
        if(dlg.actionCommand)
        {    
              return true;
        }
       dlg.dispose();
       dlg=null;
       System.gc();
       return false;
    }

    public boolean showPanelOPD()
    {   
        //DialogPrintOPD dlg = new DialogPrintOPD(frm, true,c,  phd ,opdd,hnsiriraj);//,off);
        setSize(300,150);
        setTitle("ยืนยันการพิมพ์");
       // Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       // dlg.setLocation((screenSize.width-dlg.getSfize().width)/2, screenSize.height/2);//-(28+dlg.getSize().height/2));
        Toolkit thekit = getToolkit();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();//thekit.getScreenSize();
        setBounds((screenSize.width + getSize().width + 200 )/4,(screenSize.height + getSize().height + 50)/4, getSize().width,getSize().height);
        setVisible(true);
        if(actionCommand)       return true;
        dispose();
        System.gc();
        return false;
    }
       
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JCheckBox jCheckBoxDetail;
    private javax.swing.JCheckBox jCheckBoxHead;
    private javax.swing.JCheckBox jCheckBoxHeadName;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public void setLanguage(String msg)
    {
        GuiLang.setLanguage(jButtonPrint);
	GuiLang.setLanguage(jCheckBoxDetail);
	GuiLang.setLanguage(jCheckBoxHead);
	GuiLang.setLanguage(jCheckBoxHeadName);
	GuiLang.setTextBundle(jPanel1);
    }
}
