/*
 * DialogSearchPatient.java
 *
 * Created on 19 กรกฎาคม 2547, 11:41 น.
 */

package com.hosv3.gui.dialog;

import com.hospital_os.utility.CellRendererHos;
import com.hospital_os.utility.ComboboxModel;
import com.hospital_os.utility.Gutil;
import com.hospital_os.utility.TaBleModel;
import com.hosv3.gui.component.CellRendererPatient;
import java.awt.*;

//import com.hosv3.gui.panel.transaction.*;
import com.hosv3.control.*;
import com.hosv3.utility.*;
import java.util.*;
import java.awt.event.*;
import javax.swing.*;

import com.hosv3.utility.connection.*;
import com.hospital_os.object.*;
import javax.swing.table.DefaultTableCellRenderer;



/**
 *
 * @author  Administrator
 */
public class DialogSearchPatient extends javax.swing.JDialog
{    
    //control
    int type =0;
    /** ใช้ในการควบคุมการทำงานร่วมกันของ GUI */
    javax.swing.JFrame aMain;
    Vector vPatient;
    HosControl theHC;
    PatientControl thePatientControl;
    LookupControl theLookupControl;
    VisitControl theVisitControl;
    SystemControl theSystemControl;
    DefaultTableCellRenderer rendererRight = new DefaultTableCellRenderer();
    DefaultTableCellRenderer rendererCenter = new DefaultTableCellRenderer();
    CellRendererPatient cellRendererPatient;
    // Render Hn ให้แสดงเป็นแบบสั้น sumo 26/7/2549
    CellRendererHos hnRender = new CellRendererHos(CellRendererHos.HN);
    ///////////////////////////////////////////////////////////////////
    // ตัวตรวจสอบหากค้นหาจาก Xn จะให้แสดงหมายเลข Xn แทนชื่อมารดาในตารางแสดงผลการค้นหา sumo 10/4/2549
    boolean flag = false;
    int type_gui = 0;
    private String[] column = {"HN","ชื่อ","สกุล","อายุ","เลขบัตรประชาชน","ชื่อมารดา"};
    private String[] column1 = {"HN","ชื่อ","สกุล","อายุ","เลขบัตรประชาชน","XN"};
    private String[] column2 = {"HN","ชื่อ","สกุล","อายุ","เลขบัตรประชาชน","วันเกิด"};
    private String theFamily;
    private boolean notify_mode = true;
    
     /** Creates new form DialogSearchPatient */
    public DialogSearchPatient( HosControl hc,UpdateStatus us,int type) 
    {
        super(us.getJFrame(),true);
        this.type = type; 
        initComponents();
        //this.setIconImage(us.getJFrame().getIconImage());
        this.setTitle(Constant.getTextBundle("ค้นหารายชื่อผู้ป่วย"));
        setControl(hc,hc.theUS.getJFrame(),type);
        setDefaultDialog(hc,us.getJFrame(),this.type);
    }
    
    public void setControl(HosControl hc, javax.swing.JFrame ctrl,int type){
        aMain = ctrl;
        type_gui = type;
        theHC = hc;
        theSystemControl = hc.theSystemControl;
        thePatientControl = hc.thePatientControl;
        theLookupControl = hc.theLookupControl;
        theVisitControl = hc.theVisitControl;
        hnRender = new CellRendererHos(CellRendererHos.HN,theLookupControl.getSequenceDataHN().pattern);
        cellRendererPatient = new CellRendererPatient(true);
        ComboboxModel.initComboBox(jComboBoxNCDGroup,theHC.theLookupControl.listNCDGroup());
        setLanguage("");   
        rendererRight.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
        rendererCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }
   
    
    private void setDefaultDialog(HosControl hc,JFrame ctrl,int type_gui)
    {
        this.setSize(640,480); 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();       
        this.setLocation((screenSize.width-this.getSize().width)/2, (screenSize.height-this.getSize().height)/2);
    } 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new com.hosv3.gui.component.HJTableSort();
        jPanelTop1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxNCDGroup = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNCDNumber = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonSearch1 = new javax.swing.JButton();
        jComboBoxNCDGroup1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldHcis = new javax.swing.JTextField();
        jTextFieldXn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pIDSearchPanel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHN = new javax.swing.JTextField();
        jLabelFname = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jLabelLname = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelCenter.setLayout(new java.awt.GridBagLayout());

        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableMouseReleased(evt);
            }
        });
        jTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableKeyReleased(evt);
            }
        });
        jScrollPane.setViewportView(jTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 1, 1);
        jPanelCenter.add(jScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        getContentPane().add(jPanelCenter, gridBagConstraints);

        jPanelTop1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("กลุ่ม NCD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(jComboBoxNCDGroup, gridBagConstraints);

        jLabel5.setText("หมายเลข");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jTextFieldNCDNumber.setMinimumSize(new java.awt.Dimension(60, 19));
        jTextFieldNCDNumber.setPreferredSize(new java.awt.Dimension(60, 19));
        jTextFieldNCDNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNCDNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(jTextFieldNCDNumber, gridBagConstraints);

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(jButtonSearch, gridBagConstraints);

        jButtonSearch1.setText("เคลียร์");
        jButtonSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearch1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(jButtonSearch1, gridBagConstraints);

        jComboBoxNCDGroup1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ชื่อมารดา", "XN", "วันเกิด" }));
        jComboBoxNCDGroup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNCDGroup1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(jComboBoxNCDGroup1, gridBagConstraints);

        jLabel7.setText("แสดงข้อมูล");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanelTop1.add(jPanel2, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("เลข HCIS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jTextFieldHcis.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldHcis.setMinimumSize(new java.awt.Dimension(50, 19));
        jTextFieldHcis.setPreferredSize(new java.awt.Dimension(50, 19));
        jTextFieldHcis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHcisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jTextFieldHcis, gridBagConstraints);

        jTextFieldXn.setMinimumSize(new java.awt.Dimension(50, 19));
        jTextFieldXn.setPreferredSize(new java.awt.Dimension(50, 19));
        jTextFieldXn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXnActionPerformed(evt);
            }
        });
        jTextFieldXn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldXnKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jTextFieldXn, gridBagConstraints);

        jLabel3.setText("หมายเลข XN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel2.setText("บัตรประชาชน");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel2, gridBagConstraints);

        pIDSearchPanel.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        pIDSearchPanel.setMinimumSize(new java.awt.Dimension(100, 19));
        pIDSearchPanel.setPreferredSize(new java.awt.Dimension(100, 19));
        pIDSearchPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIDSearchPanelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(pIDSearchPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelTop1.add(jPanel1, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("HN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel1, gridBagConstraints);

        jTextFieldHN.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldHN.setMinimumSize(new java.awt.Dimension(70, 19));
        jTextFieldHN.setPreferredSize(new java.awt.Dimension(70, 19));
        jTextFieldHN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHNActionPerformed(evt);
            }
        });
        jTextFieldHN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldHNKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jTextFieldHN, gridBagConstraints);

        jLabelFname.setText("Fname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jLabelFname, gridBagConstraints);

        jTextFieldFname.setMinimumSize(new java.awt.Dimension(100, 19));
        jTextFieldFname.setPreferredSize(new java.awt.Dimension(100, 19));
        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jTextFieldFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFnameKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jTextFieldFname, gridBagConstraints);

        jLabelLname.setText("Lname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jLabelLname, gridBagConstraints);

        jTextFieldLname.setMinimumSize(new java.awt.Dimension(100, 19));
        jTextFieldLname.setPreferredSize(new java.awt.Dimension(100, 19));
        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jTextFieldLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLnameKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jTextFieldLname, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelTop1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 0, 11);
        getContentPane().add(jPanelTop1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNCDNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNCDNumberActionPerformed
        setPatientV(thePatientControl.listPatientByNCD(Gutil.getGuiData(jComboBoxNCDGroup)
                ,jTextFieldNCDNumber.getText()));
    }//GEN-LAST:event_jTextFieldNCDNumberActionPerformed

    private void jButtonSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearch1ActionPerformed
        clearGUI();
    }//GEN-LAST:event_jButtonSearch1ActionPerformed

    private void pIDSearchPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIDSearchPanelActionPerformed
        setPatientV(thePatientControl.listPatientByPID(pIDSearchPanel.getText()));
    }//GEN-LAST:event_pIDSearchPanelActionPerformed

    private void jTextFieldHcisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHcisActionPerformed
        setPatientV(thePatientControl.listPatientByHcis(Gutil.getGuiData(jTextFieldHcis)));
    }//GEN-LAST:event_jTextFieldHcisActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        searchPatient();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldXnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldXnKeyReleased
        jTextFieldHN.setText("");
        jTextFieldFname.setText("");
        jTextFieldLname.setText("");
        pIDSearchPanel.setText("");
    }//GEN-LAST:event_jTextFieldXnKeyReleased

    private void jTextFieldXnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXnActionPerformed
        setPatientV(thePatientControl.listPatientByXn(jTextFieldXn.getText()));
    }//GEN-LAST:event_jTextFieldXnActionPerformed

    private void jTextFieldHNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHNKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
            jTextFieldXn.setText("");
        }
    }//GEN-LAST:event_jTextFieldHNKeyReleased

    private void jTextFieldHNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHNActionPerformed
        setPatientV(thePatientControl.listPatientByHn(jTextFieldHN.getText().trim()));
    }//GEN-LAST:event_jTextFieldHNActionPerformed

    private void jTextFieldLnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLnameKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            jTextFieldXn.setText("");
        }
    }//GEN-LAST:event_jTextFieldLnameKeyReleased

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        setPatientV(thePatientControl.listPatientByName("",jTextFieldFname.getText()
                ,jTextFieldLname.getText()));
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jTextFieldFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFnameKeyReleased
        if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            jTextFieldXn.setText("");
        }
        if(evt.getKeyCode() != KeyEvent.VK_ESCAPE) {
            jTextFieldXn.setText("");
        }
    }//GEN-LAST:event_jTextFieldFnameKeyReleased

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        setPatientV(thePatientControl.listPatientByName("",jTextFieldFname.getText()
                ,jTextFieldLname.getText()));
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    private void jTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyReleased
        if(evt.getKeyCode()==evt.VK_SPACE) {
            jTableMouseReleased(null);
        } else if(evt.getKeyCode()==evt.VK_ESCAPE) {
            this.aMain.dispose();
        }
    }//GEN-LAST:event_jTableKeyReleased

    private void jTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseReleased
        int rowPatient = jTable.getSelectedRow();
        if(rowPatient==-1) return;
        Patient pt =(Patient)vPatient.get(rowPatient);
        //ตรวจสอบว่าคนที่แสดงอยู่นี้เป็นประชากรหรือผู้ป่วยหากว่าเป็นผู้ป่วยก็ตามนี้
        //หากว่าไม่ใช่ก็ให้ทำการ ส่งข้อมูลไปให้หน้าจอ socialdata แสดงผลออกมาให้จงได้
        //คงต้องทำ managePersonNotify แล้วละ
        if(!notify_mode)
            theFamily = pt.family_id;
        if(pt.getObjectId()!=null)
            thePatientControl.readPatientByPatientID(pt.getObjectId());
        else
            thePatientControl.readFamilyByFamilyId(pt.family_id);
        this.exitForm(null);
    }//GEN-LAST:event_jTableMouseReleased
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_exitForm

    private void jComboBoxNCDGroup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNCDGroup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNCDGroup1ActionPerformed

    public void showDialog()
    {   
        this.setVisible(true);
        jTextFieldFname.requestFocus();        
    }
    public String showDialogFamily()  
    {
        this.notify_mode = false;
        theFamily = null;
        this.setVisible(true);
        jTextFieldFname.requestFocus();

        this.notify_mode = true;
        return theFamily;
    }
    private void searchPatient()
    {
        //ตรวจสอบว่า field hn เป็นค่าว่างหรือไม่
        flag = false;
        if(!jTextFieldHN.getText().equals(""))
        {
            vPatient = thePatientControl.listPatientByHn(jTextFieldHN.getText().trim());
        }     
        else if(!pIDSearchPanel.getText().equals(""))
        {  
            vPatient = thePatientControl.listPatientByPID(pIDSearchPanel.getText());
        }
        else if(!jTextFieldFname.getText().equals("")
            || !jTextFieldLname.getText().equals(""))
        {    
            vPatient = thePatientControl.listPatientByName("",jTextFieldFname.getText()
                ,jTextFieldLname.getText());           
        }
        else if(!jTextFieldXn.getText().equals(""))
        {
            vPatient = thePatientControl.listPatientByXn(jTextFieldXn.getText());
            flag = true;
        }
        else if(!this.jTextFieldNCDNumber.getText().equals(""))
        {
            vPatient = thePatientControl.listPatientByNCD(Gutil.getGuiData(jComboBoxNCDGroup)
                ,jTextFieldNCDNumber.getText());
            flag = true;
        }
        else if(!this.jTextFieldHcis.getText().equals(""))
        {
            vPatient = thePatientControl.listPatientByHcis(Gutil.getGuiData(jTextFieldHcis));
            flag = true;
        }
        else
        {
            JOptionPane.showMessageDialog(this,Constant.getTextBundle("กรุณากรอกข้อมูลอย่างน้อย 1 รายการ"), 
                    Constant.getTextBundle("คำเตือน"),JOptionPane.WARNING_MESSAGE);
        }       
        setPatientV(vPatient);
        if(vPatient != null)
        {
            if(!vPatient.isEmpty())
            {                 
                jTable.setRowSelectionInterval(0,0);
            }
        }
//        jTable.requestFocus();
    }
    
    public void gc()
    {     
         jTextFieldFname = null;
        //    jComboBoxPname = null;
         jPanelCenter = null;
         jTextFieldLname = null;
         jButtonSearch = null;
         jTable = null;
         jPanelTop1 = null;
         jScrollPane = null;
         jLabelLname = null;
    }
    
    
    /**
     * แสดงข้อมูลตารางลงตาราง 
     */
    public void setPatientV(Vector vPatient)
    {
        this.vPatient = vPatient;
       TaBleModel tm;
       if(vPatient==null)
       {
            tm = new TaBleModel(column,0);
            jTable.setModel(tm);
            return;
       }
       if(jComboBoxNCDGroup1.getSelectedIndex()==0)
            tm = new TaBleModel(column,vPatient.size());
       else if(jComboBoxNCDGroup1.getSelectedIndex()==1)
            tm = new TaBleModel(column1,vPatient.size());
       else if(jComboBoxNCDGroup1.getSelectedIndex()==2)
            tm = new TaBleModel(column2,vPatient.size());
       else
            tm = new TaBleModel(column,vPatient.size());

       String date_time = theHC.theHO.date_time;
       for(int i=0,size=vPatient.size();i<size;i++)
       {
           Patient pd = (Patient)vPatient.get(i);
           String year = DateUtil.calculateAge(pd.patient_birthday,date_time);
           if(!year.equals("")) year = year + " ปี";
           tm.setValueAt(pd.hn,i,0);
           //ค้นหาบ้านรายคนให้เรียบร้อยเพียงครั้งเดียวก็พอ
           tm.setValueAt(pd.patient_name,i,1);
           tm.setValueAt(pd.patient_last_name,i,2);
           tm.setValueAt(year,i,3);
           tm.setValueAt(pd.pid.trim(),i,4);

           if(jComboBoxNCDGroup1.getSelectedIndex()==0)
                tm.setValueAt(pd.mother_firstname,i,5);
           else if(jComboBoxNCDGroup1.getSelectedIndex()==1)
                tm.setValueAt(pd.xn,i,5);
           else if(jComboBoxNCDGroup1.getSelectedIndex()==2)
                tm.setValueAt(DateUtil.convertFieldDate(pd.patient_birthday),i,5);
           else
               tm.setValueAt(pd.mother_firstname,i,5);
       }
       jTable.setModel(tm);
       jTable.getColumnModel().getColumn(0).setPreferredWidth(100);
       jTable.getColumnModel().getColumn(0).setCellRenderer(rendererRight);
       // Render Hn ให้แสดงเป็นแบบสั้น sumo 26/7/2549
       jTable.getColumnModel().getColumn(0).setCellRenderer(hnRender);
       ///////////////////////////////////////////////////////////////
       jTable.getColumnModel().getColumn(1).setPreferredWidth(100);
       //jTable.getColumnModel().getColumn(1).setCellRenderer(cellRendererPatient);
       jTable.getColumnModel().getColumn(2).setPreferredWidth(100);
       jTable.getColumnModel().getColumn(3).setPreferredWidth(50);
       jTable.getColumnModel().getColumn(3).setCellRenderer(rendererRight);
       jTable.getColumnModel().getColumn(4).setPreferredWidth(140);
       jTable.getColumnModel().getColumn(4).setCellRenderer(rendererRight);
       jTable.getColumnModel().getColumn(5).setPreferredWidth(100);
       jTable.getColumnModel().getColumn(5).setCellRenderer(rendererCenter);
       
    }    
    /**
     * แสดงข้อมูลถ้าไม่เจอให้ส่งข้อมูลไปยัง socialData 
     */
    
     public void setLanguage(String msg)
    {   
        GuiLang.setLanguage(jLabel4);
        GuiLang.setLanguage(jLabel5);
        GuiLang.setLanguage(jLabel6);
        GuiLang.setLanguage(jButtonSearch1);
        GuiLang.setLanguage(jLabel1);
        GuiLang.setLanguage(jLabel2);
        GuiLang.setLanguage(jLabel3);
        GuiLang.setLanguage(jLabelFname);
        GuiLang.setLanguage(jLabelLname);
        GuiLang.setLanguage(jButtonSearch);
        GuiLang.setLanguage(column);
        GuiLang.setLanguage(column2);
     }
     
    /**
     *  set ค่าเพื่อให้ค้นหาเลย
     */
    public void setFnameLname(String first_name,String list_name)
    {            
        Constant.println(first_name + ": " + list_name);
        jTextFieldFname.setText(first_name);
        jTextFieldLname.setText(list_name);
        searchPatient();
    }
    /**
     *  set ค่าเพื่อให้ค้นหาเลย
     */
    public void setHNPID(String hn,String pid)
    {   
        jTextFieldHN.setText(hn);
        pIDSearchPanel.setText(pid);
        searchPatient();
    }
    
    /**
     *  ใช้ในการ clear ค่าใน form
     */
    public void clearGUI(){   
        jTextFieldFname.setText("");
        jTextFieldLname.setText("");
        jTextFieldHN.setText("");
        pIDSearchPanel.setText("");   
        jTextFieldXn.setText("");
        jTextFieldHcis.setText("");
        jTextFieldNCDNumber.setText("");
        setPatientV(null);
    }   
    
    /**
     *@Author : amp
     *@date : 09/02/2549
     *@see : เคลียร์ค่า Vector
     */
    public void setVthePatientToNull()
    {
        vPatient = null;
    }
  
        
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        DialogSearchPatient.showDialog();
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSearch1;
    private javax.swing.JComboBox jComboBoxNCDGroup;
    private javax.swing.JComboBox jComboBoxNCDGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFname;
    private javax.swing.JLabel jLabelLname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelTop1;
    private javax.swing.JScrollPane jScrollPane;
    private com.hosv3.gui.component.HJTableSort jTable;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldHN;
    private javax.swing.JTextField jTextFieldHcis;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldNCDNumber;
    private javax.swing.JTextField jTextFieldXn;
    private javax.swing.JTextField pIDSearchPanel;
    // End of variables declaration//GEN-END:variables
    
}
