/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaneNewlBornMchMother.java
 *
 * Created on 31 ม.ค. 2554, 10:03:01
 */

package com.pcu.gui.panelpcu;

import com.hospital_os.utility.TaBleModel;
import com.hosv3.utility.connection.UpdateStatus;
import com.pcu.control.HosManage;
import com.pcu.control.PCUObject;
import com.pcu.gui.dialog.HosDialog;
import com.pcu.gui.dialog.PanelChooseBornMchMother;
import com.pcu.object.AncPcu;
import com.pcu.object.BornMch;
import com.pcu.object.Pregnancy;
import java.util.Vector;

/**
 *
 * @author LionHeart
 */
public class PaneNewlBornMchMother extends javax.swing.JPanel {

    HosManage theHM;
    private HosDialog theHD;
    private UpdateStatus theUS;
    PanelChooseBornMchMother thePanelChooseBornMchMother;
    private Vector thePregnancyV;
    Vector theBornMchV;
    String[] col = {"ครรภ์ที่คลอด","LMP","EDC"};
    public PaneNewlBornMchMother() {
        initComponents();
    }
    public void setControl(HosManage hm,HosDialog hd,UpdateStatus us)
    {
        theHM = hm;
        theHD = hd;
        theUS = us;
    }
    public void setObject(PCUObject pcuo )
    {
        thePregnancyV = theHM.theHosControl.theHealthServiceControl.listPregnancyByFamilyID();
        Vector vBornMother = theHM.theHosControl.theAfterMCHMotherControl.selectBornMchMotherShowGUITableByFamilyID();
        setBornMchV(vBornMother);
    }
    public void setBornMchV(Vector bornMchV)
    {
        TaBleModel tm;
        theBornMchV = bornMchV;
        if(theBornMchV==null)
            theBornMchV = new Vector();
        tm = new TaBleModel(col,theBornMchV.size());

        for(int i=0;i<theBornMchV.size();i++)
        {
            BornMch bornMch = (BornMch) theBornMchV.get(i);
            for(int i2=0;i2<thePregnancyV.size();i2++)
            {
                Pregnancy pregnancy = (Pregnancy) thePregnancyV.get(i2);
                if(pregnancy.pregnancy_gravida_number.equals(bornMch.gravida))
                {
                    tm.setValueAt(pregnancy.pregnancy_menses_issue_date, i, 1);
                    tm.setValueAt(pregnancy.pregnancy_menses_expire_date, i, 2);
                }
            }
            tm.setValueAt(bornMch.gravida, i, 0);
        }
        jTable1.setModel(tm);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ข้อมูลการคลอด"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("การดูแลแม่หลังคลอดครั้งที่ 1"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("การดูแลแม่หลังคลอดครั้งที่ 2"));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel2.add(jScrollPane3, gridBagConstraints);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("การดูแม่หลังคลอดครั้งที่ 3"));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 3);
        add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("*ต้องการแก้ไขข้อมูลสามารถคลิ้กบนพื้นที่รายงาน");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jLabel1, gridBagConstraints);

        jButton1.setText("คลิ้กเพื่อลงข้อมูล");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel3.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int select = jTable1.getSelectedRow();
        BornMch bornMch = null;
        if(select>=0)
        {
            if(this.theBornMchV!=null&&!this.theBornMchV.isEmpty())
            {
                bornMch = (BornMch) theBornMchV.get(select);
            }
        }
        int anc_time = 0;
        if(thePanelChooseBornMchMother == null)
        {
            thePanelChooseBornMchMother = new PanelChooseBornMchMother();
            thePanelChooseBornMchMother.setControl(theHM, theHD, theUS);
        }
        //Pregnancy pregnancy,BornMch bornMch,AncPcu ancPcu

        if(thePregnancyV!=null&&!thePregnancyV.isEmpty())
        {
            Pregnancy pregnancy = (Pregnancy) thePregnancyV.get(thePregnancyV.size()-1);
            Vector anc = theHM.theHosControl.theHealthServiceControl.listAncByPregnantID(pregnancy.getObjectId());
            AncPcu ancPcu = null;
            if(anc!=null&&!anc.isEmpty())
                ancPcu = (AncPcu) anc.get(anc.size()-1);
            anc_time = anc.size();
            thePanelChooseBornMchMother.setLeftPanel(pregnancy, bornMch, ancPcu);
        }
        thePanelChooseBornMchMother.setAncTime(anc_time, 3);
        thePanelChooseBornMchMother.showDialog();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables

}
