/*
 * PanelReportPatientOverService.java
 *
 * Created on 19 ตุลาคม 2548, 18:21 น.
 */

package com.generalreport.gui.panel.report;
import com.generalreport.gui_component.TableModelGUI;
import com.generalreport.subject.ManageAllPanel;
import com.generalreport.subject.ManageGUI;
import com.generalreport.utility.GUIControl;
import com.generalreport.utility.Constant;
import com.generalreport.utility.Report;
import java.util.Vector;

import com.generalreport.control.HosManage;
import com.generalreport.utility.Language;
import com.generalreport.gui_component.DialogShowStatus;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author  tong(Padungrat)
 */
public class PanelReportPatientOverService extends javax.swing.JPanel implements 
GUIControl,ManageGUI,Runnable,ManageAllPanel {
    
    HosManage theHosManage;
    Thread theThread;
    private String startDate;
    private String endDate;
    final private String cardName;// = "TestReport";
    private DefaultTableCellRenderer rendererCenter;
    Vector vcData;
    String[] headColumn;
    Vector vcDataQuery;
    TableModelGUI theTableModelGUI;
    DialogShowStatus theDialogShowStatus;
    int language = 1;
    private String sub_fileName = "";
    private boolean isDbBackup;
    
    public PanelReportPatientOverService(HosManage hosmanage)
    {
        theHosManage = hosmanage;
        theHosManage.theHosControl.theHosSubject.theGUISubject.registerGUIManage(this);
        theHosManage.theHosControl.theHosSubject.theAllPanelSubject.registerAllPanelManage(this);
        
        cardName = ((Report)Constant.Report.get("14")).ENG_NAME;
        initComponents();
        setLanguage();
        theDialogShowStatus = new DialogShowStatus(theHosManage.theUS.getJFrame(),false,theHosManage);
    
    }
    /**run thread*/
    public void run()
    {
       queryDataByDate(startDate,endDate);
    }    
    /**
     *  ส่งชื่อของ panel ไปให้ Frame หลังที่จะใช้ในการทำ card Layout
     *  @return string เป็น ชื่อ ของ panel เป็นอังกฤษ
     */ 
    public String getCardName()
    {
        return cardName;
    }
    /**
     *  ใช้ในการรับ notify เมื่อมีการ stop service 
     */
    public void notifyStopProcess()
    {
         try
        {
              if(theThread != null)
              {
                  theThread.stop();
              }
              theThread = null;
              System.out.println("In stop in PanelReportPaymentINOUTCUP");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelShowData = new javax.swing.JPanel();
        jScrollPanelShowData = new javax.swing.JScrollPane();
        jTableShow = new javax.swing.JTable();
        jPanelControl = new javax.swing.JPanel();
        jLabelService = new javax.swing.JLabel();
        jLabelTimes = new javax.swing.JLabel();
        integerTextFieldTimes = new com.hospital_os.utility.IntegerTextField();

        setLayout(new java.awt.BorderLayout());

        jPanelShowData.setLayout(new java.awt.GridBagLayout());

        jTableShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPanelShowData.setViewportView(jTableShow);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelShowData.add(jScrollPanelShowData, gridBagConstraints);

        add(jPanelShowData, java.awt.BorderLayout.CENTER);

        jPanelControl.setLayout(new java.awt.GridBagLayout());

        jLabelService.setText("OverServices");
        jPanelControl.add(jLabelService, new java.awt.GridBagConstraints());

        jLabelTimes.setText("Times");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanelControl.add(jLabelTimes, gridBagConstraints);

        integerTextFieldTimes.setColumns(3);
        integerTextFieldTimes.setText("integerTextField1");
        integerTextFieldTimes.setMinimumSize(new java.awt.Dimension(40, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanelControl.add(integerTextFieldTimes, gridBagConstraints);

        add(jPanelControl, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents
    
    /**ใช้ในการรับข้อมูลจาก การค้นหา และส่งค่าเข้ามา panel นี้
     *  เพื่อให้ทำการ Query และค้นหารายการตามข้อกำหนดของ panel
     *  @param startDate เป็น String เป็นวันที่เริ่มต้น อยู่ในรูปแบบ yyyy-mm-dd
     *  @param endDate เป็น String เป็นวันที่สิ้นสุด อยู่ในรูปแบบ yyyy-mm-dd
     */
    public void setQueryReport(String startDate, String endDate, boolean dbBackup)
    {
        this.startDate = startDate;
        this.endDate = endDate;
        isDbBackup = dbBackup;
        //setFileDescription();
        startQuery();
        // queryDataByDate(startDate,endDate);
    }
    
    /**
     *  ใช้ในการเริ่มให้ thread เริ่มทำงาน จะต้องมาเรียก method นี้ทุกครั้ง
     * 
     */
    private void startQuery()
    {
        theThread = new Thread(this);
        theThread.start();
    }
    /**
     *  ส่งค่าข้อมูลกลับไปยัง Frame หลักเมื่อมีการบันทึกออกมาเป็นไฟล์
     *  @return Vector ของ ข้อมูลที่ Query ออกมาได้
     */
    public Vector getData()
    {
        return this.vcData;
    }
    
    /**ตรวจสอบ จำนวนที่กรอกต้อมีค่าหรือมีมากกว่าหรือเท่ากับ 0*/
    private boolean checkServiceTimes()
    {   boolean result = false;
        String times = integerTextFieldTimes.getText();
        if(times.length() > 0)
        {
            result = true;
        }
        else
        {
            integerTextFieldTimes.requestFocus();
        }
        return result;
    }
    
    /***/
    private void queryDataByDate(String startDate, String endDate)
    {
        sub_fileName = integerTextFieldTimes.getText();
        
        if(checkServiceTimes())
        {
            theDialogShowStatus.setVisible(false);
            theDialogShowStatus.showDialog("กรุณารอสักครู่",false);

            vcData = theHosManage.theHosControl.theRPPatientOverServiceControl.selecPatientOverServiceByDate(startDate,endDate, integerTextFieldTimes.getText(),isDbBackup);
            headColumn = new String[] {""};
            vcDataQuery = null;
            if(vcData != null)
            {

                headColumn = (String[])vcData.get(0);
                vcDataQuery = (Vector)vcData.get(1);
            }

            showDataInTable(headColumn, vcDataQuery);
            
           // theHosManage.theHosControl.theTestReportControl.stop();
          //  theDialogShowStatus.showDialog("กรุณารอสักครู่",true);
            theDialogShowStatus.setVisible(false);       
        }
        else
        {
            showMessageServiceTimesNoData();
        }
    }
    
    private void showMessageServiceTimesNoData()
    {
        javax.swing.JOptionPane.showMessageDialog(this,Language.getTextBundle("ServiceTimesNoData", language),Language.getTextBundle("Warning", language),javax.swing.JOptionPane.OK_OPTION);
    }
    private void showDataInTable(String[] columnname,Vector vc)
    {
             
        String[] col = columnname;      
        
        int size = 0;
        if(vc != null)
        {   theTableModelGUI= new TableModelGUI(col,vc.size());
            size = vc.size();
            
            //วนลูป ต่อ 1 แถว
            for(int i=0 ;i<size; i++)
            {    //วนลูปตของ column
                String[] rowdata = (String[])vc.get(i);

                for(int j = 0 ; j < rowdata.length ;j++)
                {
                    
                    theTableModelGUI.setValueAt(rowdata[j],i,j);                        
                }
                theTableModelGUI.setEditingCol(rowdata.length+1);
                rowdata = null;
                
                //    tm.setValueAt(((OrderItem)this.theOrderControl.listOrderItemByItem(p.getObjectId(),this.vn)).refer_out,i,2);
            }                
                       
        }
        else
        {   theTableModelGUI= new TableModelGUI(col,0);            
        }
        this.jTableShow.setModel(theTableModelGUI);
        if(col!= null && col.length!= 0)
        {
            setTableListReportPattern(col);
        }
        sendDataToMainReport(size);
    }
      /**ใช้ในการแสดงความกว้างของคอลัมน์
       *@param col เป็น Array ของ String ที่เก็บหัว column สำหรับนำมานับจำนวน Column ที่ต้องสร้างในตาราง
       *
       */
    private void setTableListReportPattern(String [] col)
    {
        if(rendererCenter == null )
        {
            rendererCenter = new DefaultTableCellRenderer();
        }
        rendererCenter.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        
        String[] col_number = col;
        for(int i=0;i<col_number.length;i++)
        {
            if(i == 0)
            {
                jTableShow.getColumnModel().getColumn(i).setPreferredWidth(100);
            }
            else if(i == 6)
            {
                jTableShow.getColumnModel().getColumn(i).setCellRenderer(rendererCenter);
                jTableShow.getColumnModel().getColumn(i).setPreferredWidth(20);
            }
            else
            {
                 jTableShow.getColumnModel().getColumn(i).setPreferredWidth(20);
            }
            
        }
    }
    /**
     *  ใช้ในการส่งสถานะให้แสดง ปุ่มบันทึกหรือไม่ โดยจะตรวจสอบจาก size ของตาราง
     */
    private void sendDataToMainReport(int size)
    {
        theHosManage.theHosControl.theHosSubject.theMainReportSubject.notifyShowSaveToFile(false);
        if(size >0)
        {
            theHosManage.theHosControl.theHosSubject.theMainReportSubject.notifyShowSaveToFile(true);
        }
    }
    
    /**ใช้ในการ Clear ข้อมูลที่อยู่บนตาราง*/
    private void clearDataGUI()
    {
        integerTextFieldTimes.setText("0");
        showDataInTable(new String[] {""}, null);
        System.out.println("Clear Data in GUI");
    }
    public void notifySetInitAllGUI()
    {
        clearDataGUI();
    }
    private void setLanguage()
    {
        this.jLabelService.setText(Language.getTextBundle(this.jLabelService.getText(),language));
        this.jLabelTimes.setText(Language.getTextBundle(this.jLabelTimes.getText(),language));
    }
    
    /**
     *ส่งชื่อของไฟล์ เพื่อนำไปต่อเป็นชื่อไฟล์ที่ได้เซ้ตไว้แล้ว 
     * เพื่อระบุให้ชัดเจนว่ารายงานที่ถูก save เป็นรายงานอะไร
     *@return String เป็นชื่อไฟลืที่ต้องการนำไปต่อ
     */
    public String getFileName()
    {
        return sub_fileName;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hospital_os.utility.IntegerTextField integerTextFieldTimes;
    private javax.swing.JLabel jLabelService;
    private javax.swing.JLabel jLabelTimes;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelShowData;
    private javax.swing.JScrollPane jScrollPanelShowData;
    private javax.swing.JTable jTableShow;
    // End of variables declaration//GEN-END:variables
    
}
