drop table temp_village;
CREATE TABLE temp_village (
    t_health_village_id character varying(255) NOT NULL,
    village_name character varying(255),
    village_moo character varying(255),
    b_health_village_location_id character varying(255),
    village_staff_record character varying(255),
    village_staff_modify character varying(255),
    village_staff_cancel character varying(255),
    village_record_date_time character varying(255),
    village_modify_date_time character varying(255),
    village_cancel_date_time character varying(255),
    village_active character varying(255),
    village_number character varying(255),
    village_ampur character varying(255) DEFAULT ''::character varying,
    village_changwat character varying(255) DEFAULT ''::character varying,
    village_tambon character varying(255) DEFAULT ''::character varying
);

ALTER TABLE ONLY temp_village
    ADD CONSTRAINT temp_village_pkey PRIMARY KEY (t_health_village_id);


insert into temp_village (select * from t_health_village group by 
t_health_village_id,village_name,village_moo,b_health_village_location_id
,village_staff_record,    village_staff_modify,    village_staff_cancel,    village_record_date_time,    village_modify_date_time,    village_cancel_date_time,    village_active,    village_number,    village_ampur,    village_changwat,    village_tambon);


ALTER Table t_health_village RENAME TO t_health_village_old;
ALTER Table temp_village RENAME TO t_health_village;
----------------------------------------------------------------------------------------------------------------
drop table temp_home;
CREATE TABLE temp_home (
    t_health_home_id character varying(255) NOT NULL,
    b_visit_office_id character varying(255),
    health_home_number character varying(255),
    health_home_house character varying(255),
    health_home_moo character varying(255),
    health_home_road character varying(255),
    health_home_tambon character varying(255),
    health_home_amphur character varying(255),
    health_home_changwat character varying(255),
    health_home_family character varying(255),
    health_home_responsible_zone character varying(255),
    health_home_volunteer character varying(255),
    health_home_volunteer_name character varying(255),
    health_home_owner character varying(255),
    health_home_owner_number character varying(255),
    f_health_home_charactor_id character varying(255),
    f_health_home_community_charac_id character varying(255),
    t_health_village_id character varying(255),
    home_staff_record character varying(255),
    home_staff_modify character varying(255),
    home_staff_cancel character varying(255),
    home_record_date_time character varying(255),
    home_modify_date_time character varying(255),
    home_cancel_date_time character varying(255),
    home_active character varying(255),
    home_serial serial NOT NULL
);

ALTER TABLE ONLY temp_home
    ADD CONSTRAINT temp_home_pkey PRIMARY KEY (t_health_home_id);

insert into temp_home    (  t_health_home_id,
    b_visit_office_id ,
    health_home_number ,
    health_home_house ,
    health_home_moo ,
    health_home_road ,
    health_home_tambon ,
    health_home_amphur ,
    health_home_changwat ,
    health_home_family ,
    health_home_responsible_zone ,
    health_home_volunteer ,
    health_home_volunteer_name ,
    health_home_owner ,
    health_home_owner_number ,
    f_health_home_charactor_id ,
    f_health_home_community_charac_id ,
    t_health_village_id ,
    home_staff_record ,
    home_staff_modify ,
    home_staff_cancel ,
    home_record_date_time ,
    home_modify_date_time ,
    home_cancel_date_time ,
    home_active)
    
    (select t_health_home_id,
    b_visit_office_id ,
    health_home_number ,
    health_home_house ,
    health_home_moo ,
    health_home_road ,
    health_home_tambon ,
    health_home_amphur ,
    health_home_changwat ,
    health_home_family ,
    health_home_responsible_zone ,
    health_home_volunteer ,
    health_home_volunteer_name ,
    health_home_owner ,
    health_home_owner_number ,
    f_health_home_charactor_id ,
    f_health_home_community_charac_id ,
    t_health_village_id ,
    home_staff_record ,
    home_staff_modify ,
    home_staff_cancel ,
    home_record_date_time ,
    home_modify_date_time ,
    home_cancel_date_time ,
    home_active  from t_health_home group by 
t_health_home_id,
    b_visit_office_id ,
    health_home_number ,
    health_home_house ,
    health_home_moo ,
    health_home_road ,
    health_home_tambon ,
    health_home_amphur ,
    health_home_changwat ,
    health_home_family ,
    health_home_responsible_zone ,
    health_home_volunteer ,
    health_home_volunteer_name ,
    health_home_owner ,
    health_home_owner_number ,
    f_health_home_charactor_id ,
    f_health_home_community_charac_id ,
    t_health_village_id ,
    home_staff_record ,
    home_staff_modify ,
    home_staff_cancel ,
    home_record_date_time ,
    home_modify_date_time ,
    home_cancel_date_time ,
    home_active );

ALTER Table t_health_home RENAME TO t_health_home_old;
ALTER Table temp_home RENAME TO t_health_home;

----------------------------------------------------------------------------------------------------------------
drop table temp_family;
CREATE TABLE temp_family (
    t_health_family_id character varying(255) NOT NULL,
    t_health_home_id character varying(255),
    t_patient_id character varying(255),
    patient_hn character varying(255),
    t_health_family_number character varying(255),
    patient_pid character varying(255),
    f_prefix_id character varying(255),
    patient_name character varying(255),
    patient_last_name character varying(255),
    patient_birthday character varying(255),
    patient_birthday_true character varying(255),
    f_sex_id character varying(255),
    f_patient_marriage_status_id character varying(255),
    f_patient_education_type_id character varying(255),
    f_patient_occupation_id character varying(255),
    f_patient_nation_id character varying(255),
    f_patient_race_id character varying(255),
    f_patient_religion_id character varying(255),
    f_patient_family_status_id character varying(255),
    patient_father_firstname character varying(255),
    patient_father_lastname character varying(255),
    patient_father_pid character varying(255),
    patient_mother_firstname character varying(255),
    patient_mother_lastname character varying(255),
    patient_mother_pid character varying(255),
    patient_couple_firstname character varying(255),
    patient_couple_lastname character varying(255),
    patient_couple_id character varying(255),
    patient_work_office character varying(255),
    f_patient_blood_group_id character varying(255),
    f_patient_area_status_id character varying(255),
    record_date_time character varying(255),
    modify_date_time character varying(255),
    cancel_date_time character varying(255),
    health_family_staff_record character varying(255),
    health_family_staff_modify character varying(255),
    health_family_staff_cancel character varying(255),
    health_family_active character varying(255),
    health_family_hn_hcis character varying(255),
    f_patient_discharge_status_id character varying(255) DEFAULT ''::character varying,
    patient_discharge_date_time character varying(255) DEFAULT ''::character varying,
    patient_move_in_date_time character varying(255) DEFAULT ''::character varying
);

ALTER TABLE ONLY temp_family
    ADD CONSTRAINT temp_family_pkey PRIMARY KEY (t_health_family_id);

insert into temp_family   (t_health_family_id,
    t_health_home_id,
    t_patient_id,
    patient_hn,
    t_health_family_number,
    patient_pid,
    f_prefix_id,
    patient_name,
    patient_last_name,
    patient_birthday,
    patient_birthday_true,
    f_sex_id,
    f_patient_marriage_status_id,
    f_patient_education_type_id,
    f_patient_occupation_id,
    f_patient_nation_id,
    f_patient_race_id,
    f_patient_religion_id,
    f_patient_family_status_id,
    patient_father_firstname,
    patient_father_lastname,
    patient_father_pid,
    patient_mother_firstname,
    patient_mother_lastname,
    patient_mother_pid,
    patient_couple_firstname,
    patient_couple_lastname,
    patient_couple_id,
    patient_work_office,
    f_patient_blood_group_id,
    f_patient_area_status_id,
    record_date_time,
    cancel_date_time,
    health_family_staff_record,
    health_family_staff_cancel,
    health_family_active,
    health_family_hn_hcis,
    f_patient_discharge_status_id,
    patient_discharge_date_time,
    patient_move_in_date_time)
    
    (select     t_health_family_id,
    t_health_home_id,
    t_patient_id,
    patient_hn,
    t_health_family_number,
    patient_pid,
    f_prefix_id,
    patient_name,
    patient_last_name,
    patient_birthday,
    patient_birthday_true,
    f_sex_id,
    f_patient_marriage_status_id,
    f_patient_education_type_id,
    f_patient_occupation_id,
    f_patient_nation_id,
    f_patient_race_id,
    f_patient_religion_id,
    f_patient_family_status_id,
    patient_father_firstname,
    patient_father_lastname,
    patient_father_pid,
    patient_mother_firstname,
    patient_mother_lastname,
    patient_mother_pid,
    patient_couple_firstname,
    patient_couple_lastname,
    patient_couple_id,
    patient_work_office,
    f_patient_blood_group_id,
    f_patient_area_status_id,
    record_date_time,
    cancel_date_time,
    health_family_staff_record,
    health_family_staff_cancel,
    health_family_active,
    health_family_hn_hcis,
    f_patient_discharge_status_id,
    patient_discharge_date_time,
    patient_move_in_date_time
    
    from t_health_family group by 
    t_health_family_id,
    t_health_home_id,
    t_patient_id,
    patient_hn,
    t_health_family_number,
    patient_pid,
    f_prefix_id,
    patient_name,
    patient_last_name,
    patient_birthday,
    patient_birthday_true,
    f_sex_id,
    f_patient_marriage_status_id,
    f_patient_education_type_id,
    f_patient_occupation_id,
    f_patient_nation_id,
    f_patient_race_id,
    f_patient_religion_id,
    f_patient_family_status_id,
    patient_father_firstname,
    patient_father_lastname,
    patient_father_pid,
    patient_mother_firstname,
    patient_mother_lastname,
    patient_mother_pid,
    patient_couple_firstname,
    patient_couple_lastname,
    patient_couple_id,
    patient_work_office,
    f_patient_blood_group_id,
    f_patient_area_status_id,
    record_date_time,
    cancel_date_time,
    health_family_staff_record,
    health_family_staff_cancel,
    health_family_active,
    health_family_hn_hcis,
    f_patient_discharge_status_id,
    patient_discharge_date_time,
    patient_move_in_date_time);

ALTER Table t_health_family RENAME TO t_health_family_old;
ALTER Table temp_family RENAME TO t_health_family;

----------------------------------------------------------------------------------------------------------------