/*
 * SetupContract.java
 *
 * Created on 29 ตุลาคม 2546, 14:23 น.
 */
package com.hosv3.gui.panel.setup;

import java.util.Vector;
import com.hosv3.control.*;
import com.hosv3.utility.connection.*;
import com.hosv3.utility.*;
import com.hospital_os.utility.ComboboxModel;
import com.hospital_os.utility.Gutil;
import com.hospital_os.utility.TaBleModel;
import com.hospital_os.object.*;
import com.hosv3.utility.Constant;
/**
 *
 * @panel author : amp
 *
 *
 * @deprecated henbe unused old pattern
 *@author by  : pee
 */
public class PanelSetupContract extends javax.swing.JPanel
{
    UpdateStatus theUS;
   public Contract theContract;
   public ContractAdjust theContractAdjust;
   public SetupControl theSetupControl;
   public LookupControl theLookupControl;
   public Vector gContract = new Vector();
   public Vector gItem;
   public Vector cData;
   public String code;
   int offset = 24;
   int next = 0;
   int prev = 0;
   public int  save=0;
   String[] col = {"รหัส","ชื่อส่วนลด"};
   String[] column = {"กลุ่มรายการ","ส่วนลด(%)"};
    /** Creates new form SetupContract */
    public PanelSetupContract() {
        initComponents();
        setLanguage();
    }
    public PanelSetupContract(HosControl hc,UpdateStatus us){
        initComponents();
        setLanguage();
	setControl(hc,us);
    }
   /**
     *@Author : amp
     *@date : 29/02/2549
     *@see : จัดการเกี่ยวกับภาษา    
     */
    private void setLanguage()
    {
        GuiLang.setLanguage(jLabel5);
        GuiLang.setLanguage(jLabelICD9code);
        GuiLang.setLanguage(jButtonSearch);
        GuiLang.setLanguage(jLabel1);        
        GuiLang.setLanguage(jLabel2);
        GuiLang.setLanguage(jButtonSave);
        GuiLang.setLanguage(jLabel3);
        GuiLang.setLanguage(jLabel6);        
        GuiLang.setLanguage(jLabel7);
        GuiLang.setLanguage(jCheckBoxDraw);
        GuiLang.setLanguage(jButtonSave1);  
        GuiLang.setLanguage(col);
        GuiLang.setLanguage(column);
    }    
    ////////////////////////////////////////	public void setControl(HosControl hc,UpdateStatus us){
    public void setControl(HosControl hc,UpdateStatus us){
        theUS = us;
        this.jTableGroupContract.setGuiMode(true);
        hc.theHS.theSetupSubject.addpanelrefrash(this);
        hc.theHS.theSetupSubject.addForLiftAttach(this);
        theSetupControl = hc.theSetupControl;
        theLookupControl = hc.theLookupControl;
       // searchContract();
        setEnableDataGroup(false);
        setEnableGroup(false);
        setupLookup();
    }
     public void setupLookup(){
         ComboboxModel.initComboBox(jComboBoxCategory,theLookupControl.listCategoryGroupItem());
     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        defaultFont1 = new com.hospital_os.gui.font.DefaultFont();
        fontFormatTitle1 = new com.hospital_os.gui.font.FontFormatTitle();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelICD9code = new javax.swing.JLabel();
        jTextFieldKeyword = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGroupContract = new com.hosv3.gui.component.HJTableSort();
        jPanel10 = new javax.swing.JPanel();
        jButtonNext = new javax.swing.JButton();
        jButtonPrev = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableContractData = new com.hosv3.gui.component.HJTableSort();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxCategory = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxDraw = new javax.swing.JCheckBox();
        jTextFieldContract = new com.hospital_os.utility.DoubleTextField();
        jPanel11 = new javax.swing.JPanel();
        jButtonAdd1 = new javax.swing.JButton();
        jButtonDel1 = new javax.swing.JButton();
        jButtonSave1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setEnabled(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(422, 670));
        jPanel1.setPreferredSize(new java.awt.Dimension(685, 670));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(fontFormatTitle1);
        jLabel5.setText("\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e2a\u0e48\u0e27\u0e19\u0e25\u0e14");
        jPanel6.add(jLabel5, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel6, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(300, 25));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 404));
        jLabelICD9code.setFont(defaultFont1);
        jLabelICD9code.setText("\u0e04\u0e49\u0e19\u0e2b\u0e32");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 11);
        jPanel3.add(jLabelICD9code, gridBagConstraints);

        jTextFieldKeyword.setFont(defaultFont1);
        jTextFieldKeyword.setMaximumSize(new java.awt.Dimension(150, 24));
        jTextFieldKeyword.setMinimumSize(new java.awt.Dimension(45, 21));
        jTextFieldKeyword.setPreferredSize(new java.awt.Dimension(45, 21));
        jTextFieldKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeywordActionPerformed(evt);
            }
        });
        jTextFieldKeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldKeywordKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel3.add(jTextFieldKeyword, gridBagConstraints);

        jButtonSearch.setFont(defaultFont1);
        jButtonSearch.setText("\u0e04\u0e49\u0e19\u0e2b\u0e32");
        jButtonSearch.setMaximumSize(new java.awt.Dimension(67, 25));
        jButtonSearch.setMinimumSize(new java.awt.Dimension(67, 25));
        jButtonSearch.setPreferredSize(new java.awt.Dimension(67, 25));
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jButtonSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonSearchKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel3.add(jButtonSearch, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 22));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 80));
        jTableGroupContract.setFont(defaultFont1);
        jTableGroupContract.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableGroupContractKeyReleased(evt);
            }
        });
        jTableGroupContract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableGroupContractMouseReleased(evt);
            }
        });

        jScrollPane1.setViewportView(jTableGroupContract);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hospital_os/images/Forward16.gif")));
        jButtonNext.setMaximumSize(new java.awt.Dimension(24, 24));
        jButtonNext.setMinimumSize(new java.awt.Dimension(24, 24));
        jButtonNext.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jButtonNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonNextKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel10.add(jButtonNext, gridBagConstraints);

        jButtonPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hospital_os/images/Back16.gif")));
        jButtonPrev.setMaximumSize(new java.awt.Dimension(24, 24));
        jButtonPrev.setMinimumSize(new java.awt.Dimension(24, 24));
        jButtonPrev.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevActionPerformed(evt);
            }
        });
        jButtonPrev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonPrevKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel10.add(jButtonPrev, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jPanel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        jPanel8.setMinimumSize(new java.awt.Dimension(350, 360));
        jPanel8.setPreferredSize(new java.awt.Dimension(350, 391));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(350, 120));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 45));
        jLabel1.setFont(defaultFont1);
        jLabel1.setText("\u0e23\u0e2b\u0e31\u0e2a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel1, gridBagConstraints);

        jTextFieldCode.setFont(defaultFont1);
        jTextFieldCode.setMaximumSize(new java.awt.Dimension(150, 24));
        jTextFieldCode.setMinimumSize(new java.awt.Dimension(45, 21));
        jTextFieldCode.setPreferredSize(new java.awt.Dimension(45, 21));
        jTextFieldCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodeKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jTextFieldCode, gridBagConstraints);

        jLabel2.setFont(defaultFont1);
        jLabel2.setText("\u0e0a\u0e37\u0e48\u0e2d\u0e2a\u0e48\u0e27\u0e19\u0e25\u0e14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel2, gridBagConstraints);

        jTextFieldName.setFont(defaultFont1);
        jTextFieldName.setMaximumSize(new java.awt.Dimension(150, 24));
        jTextFieldName.setMinimumSize(new java.awt.Dimension(45, 21));
        jTextFieldName.setPreferredSize(new java.awt.Dimension(45, 21));
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jTextFieldName, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButtonAdd.setFont(defaultFont1);
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hosv3/gui/images/plus16.gif")));
        jButtonAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAdd.setMaximumSize(new java.awt.Dimension(24, 24));
        jButtonAdd.setMinimumSize(new java.awt.Dimension(24, 24));
        jButtonAdd.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jButtonAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonAddKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel4.add(jButtonAdd, gridBagConstraints);

        jButtonSave.setFont(defaultFont1);
        jButtonSave.setText("\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01");
        jButtonSave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSave.setMinimumSize(new java.awt.Dimension(61, 24));
        jButtonSave.setPreferredSize(new java.awt.Dimension(61, 24));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel4.add(jButtonSave, gridBagConstraints);

        jButtonDel.setFont(defaultFont1);
        jButtonDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hosv3/gui/images/minus16.gif")));
        jButtonDel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDel.setMaximumSize(new java.awt.Dimension(24, 24));
        jButtonDel.setMinimumSize(new java.awt.Dimension(24, 24));
        jButtonDel.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });
        jButtonDel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonDelKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel4.add(jButtonDel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel7.add(jPanel2, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setMinimumSize(new java.awt.Dimension(350, 250));
        jPanel5.setPreferredSize(new java.awt.Dimension(350, 250));
        jLabel3.setFont(defaultFont1);
        jLabel3.setText("\u0e04\u0e23\u0e2d\u0e1a\u0e04\u0e25\u0e38\u0e21\u0e01\u0e25\u0e38\u0e48\u0e21\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel5.add(jLabel3, gridBagConstraints);

        jTableContractData.setFont(defaultFont1);
        jTableContractData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableContractDataKeyReleased(evt);
            }
        });
        jTableContractData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableContractDataMouseReleased(evt);
            }
        });

        jScrollPane2.setViewportView(jTableContractData);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel5.add(jScrollPane2, gridBagConstraints);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(defaultFont1);
        jLabel6.setText("\u0e01\u0e25\u0e38\u0e48\u0e21\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel9.add(jLabel6, gridBagConstraints);

        jComboBoxCategory.setFont(defaultFont1);
        jComboBoxCategory.setMaximumSize(new java.awt.Dimension(150, 24));
        jComboBoxCategory.setMinimumSize(new java.awt.Dimension(150, 24));
        jComboBoxCategory.setPreferredSize(new java.awt.Dimension(150, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel9.add(jComboBoxCategory, gridBagConstraints);

        jLabel7.setFont(defaultFont1);
        jLabel7.setText("\u0e2a\u0e48\u0e27\u0e19\u0e25\u0e14(%)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel9.add(jLabel7, gridBagConstraints);

        jCheckBoxDraw.setFont(defaultFont1);
        jCheckBoxDraw.setText("\u0e40\u0e1a\u0e34\u0e01\u0e08\u0e48\u0e32\u0e22\u0e44\u0e14\u0e49");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel9.add(jCheckBoxDraw, gridBagConstraints);

        jTextFieldContract.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldContract.setFont(defaultFont1);
        jTextFieldContract.setMinimumSize(new java.awt.Dimension(45, 21));
        jTextFieldContract.setPreferredSize(new java.awt.Dimension(45, 21));
        jTextFieldContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContractActionPerformed(evt);
            }
        });
        jTextFieldContract.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldContractKeyReleased(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel9.add(jTextFieldContract, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel5.add(jPanel9, gridBagConstraints);

        jPanel11.setLayout(new java.awt.GridBagLayout());

        jButtonAdd1.setFont(defaultFont1);
        jButtonAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hosv3/gui/images/plus16.gif")));
        jButtonAdd1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAdd1.setMaximumSize(new java.awt.Dimension(24, 24));
        jButtonAdd1.setMinimumSize(new java.awt.Dimension(24, 24));
        jButtonAdd1.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdd1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 2);
        jPanel11.add(jButtonAdd1, gridBagConstraints);

        jButtonDel1.setFont(defaultFont1);
        jButtonDel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hosv3/gui/images/minus16.gif")));
        jButtonDel1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDel1.setMaximumSize(new java.awt.Dimension(24, 24));
        jButtonDel1.setMinimumSize(new java.awt.Dimension(24, 24));
        jButtonDel1.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDel1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel11.add(jButtonDel1, gridBagConstraints);

        jButtonSave1.setFont(defaultFont1);
        jButtonSave1.setText("\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01");
        jButtonSave1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSave1.setMaximumSize(new java.awt.Dimension(63, 26));
        jButtonSave1.setMinimumSize(new java.awt.Dimension(61, 24));
        jButtonSave1.setPreferredSize(new java.awt.Dimension(61, 24));
        jButtonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSave1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        jPanel11.add(jButtonSave1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel5.add(jPanel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel7.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel8.add(jPanel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel1.add(jPanel8, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonDelKeyReleased
        if(evt.getKeyCode()==evt.VK_RIGHT)
            jButtonSave.requestFocus();
        if(evt.getKeyCode()==evt.VK_LEFT)
            jButtonAdd.requestFocus();
        if(evt.getKeyCode()==evt.VK_ESCAPE)
            cancelinsertGroupContract();
    }//GEN-LAST:event_jButtonDelKeyReleased

    private void jButtonAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAddKeyReleased
        if(evt.getKeyCode()==evt.VK_RIGHT)
            jButtonDel.requestFocus();
        if(evt.getKeyCode()==evt.VK_LEFT)
            jButtonSave.requestFocus();
        if(evt.getKeyCode()==evt.VK_ESCAPE)
            cancelinsertGroupContract();
    }//GEN-LAST:event_jButtonAddKeyReleased

    private void jButtonSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSearchKeyReleased
        if(evt.getKeyCode()==evt.VK_DOWN)
            jTableGroupContract.requestFocus();
        if(evt.getKeyCode()==evt.VK_UP)
            jTextFieldKeyword.requestFocus();
    }//GEN-LAST:event_jButtonSearchKeyReleased

    private void jTextFieldCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodeKeyReleased
        if(evt.getKeyCode()==evt.VK_DOWN)
            jTextFieldName.requestFocus();
        if(evt.getKeyCode()==evt.VK_UP || evt.getKeyCode()==evt.VK_ESCAPE)
            cancelinsertGroupContract();
    }//GEN-LAST:event_jTextFieldCodeKeyReleased

    private void jTextFieldKeywordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeywordKeyReleased
        if(evt.getKeyCode()==evt.VK_UP || evt.getKeyCode()==evt.VK_DOWN)
            jTableGroupContract.requestFocus();
    }//GEN-LAST:event_jTextFieldKeywordKeyReleased

    private void jButtonNextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNextKeyReleased
        if(evt.getKeyCode()==evt.VK_UP || evt.getKeyCode()==evt.VK_DOWN)
            jTableGroupContract.requestFocus();
        if(evt.getKeyCode()==evt.VK_LEFT)
        {
            jButtonPrev.requestFocus();
            jButtonPrevActionPerformed(null);
        }
        if(evt.getKeyCode()==evt.VK_RIGHT)
            jButtonNextActionPerformed(null);
    }//GEN-LAST:event_jButtonNextKeyReleased

    private void jButtonPrevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPrevKeyReleased
        if(evt.getKeyCode()==evt.VK_UP || evt.getKeyCode()==evt.VK_DOWN)
            jTableGroupContract.requestFocus();

        if(evt.getKeyCode()==evt.VK_RIGHT)
        {
            jButtonNext.requestFocus();
            jButtonNextActionPerformed(null);
        }
        if(evt.getKeyCode()==evt.VK_LEFT)
        {
            jButtonPrevActionPerformed(null);
        } 
    }//GEN-LAST:event_jButtonPrevKeyReleased

    private void jTextFieldContractKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContractKeyReleased
        if(evt.getKeyCode()==evt.VK_UP || evt.getKeyCode()==evt.VK_DOWN)
            this.jTableContractData.requestFocus();
    }//GEN-LAST:event_jTextFieldContractKeyReleased

    private void jTextFieldNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyReleased
        if(evt.getKeyCode()==evt.VK_UP)
            jTextFieldCode.requestFocus();
        if(evt.getKeyCode()==evt.VK_DOWN || evt.getKeyCode()==evt.VK_TAB)
            jButtonSave.requestFocus();
        if(evt.getKeyCode()==evt.VK_ESCAPE)
            cancelinsertGroupContract();
    }//GEN-LAST:event_jTextFieldNameKeyReleased

    private void jTextFieldContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContractActionPerformed
        this.jButtonSave1ActionPerformed(null);
    }//GEN-LAST:event_jTextFieldContractActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        this.jButtonSaveActionPerformed(null);
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        setTableContractGroup(gContract,0);
    }//GEN-LAST:event_jButtonPrevActionPerformed
    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        setTableContractGroup(gContract,1);
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jTableContractDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableContractDataKeyReleased
        if(evt.getKeyCode()==evt.VK_UP || evt.getKeyCode()==evt.VK_DOWN)
            selectContractData();
        if(evt.getKeyCode()==evt.VK_SPACE)
            jTextFieldContract.requestFocus();
        if(evt.getKeyCode()==evt.VK_INSERT)
            jButtonAdd1ActionPerformed(null);
        if(evt.getKeyCode()==evt.VK_DELETE)
            jButtonDel1ActionPerformed(null);
        if(evt.getKeyCode()==evt.VK_ESCAPE)
            jTableGroupContract.requestFocus();
    }//GEN-LAST:event_jTableContractDataKeyReleased
    private void jTableGroupContractKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableGroupContractKeyReleased
        if(evt.getKeyCode()==evt.VK_UP || evt.getKeyCode()==evt.VK_DOWN)
            selectGroupContract();
        if(evt.getKeyCode()==evt.VK_INSERT)
            jButtonAddActionPerformed(null);
        if(evt.getKeyCode()==evt.VK_DELETE)
            jButtonDelActionPerformed(null);
        if(evt.getKeyCode()==evt.VK_SPACE)
           jTableContractData.requestFocus();
    }//GEN-LAST:event_jTableGroupContractKeyReleased
    private void jTextFieldKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKeywordActionPerformed
        // Add your handling code here:
        searchContract();
    }//GEN-LAST:event_jTextFieldKeywordActionPerformed
    private void jButtonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSave1ActionPerformed
        saveContractAdjust();
        this.jTableContractData.requestFocus();
    }//GEN-LAST:event_jButtonSave1ActionPerformed
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        saveGroup();
        this.jTableContractData.requestFocus();
        setEnableGroup(false);
        setEnableDataGroup(true);
    }//GEN-LAST:event_jButtonSaveActionPerformed
    private void jTableContractDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableContractDataMouseReleased
        selectContractData();
        jTextFieldContract.requestFocus();
    }//GEN-LAST:event_jTableContractDataMouseReleased
    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
         int row = jTableGroupContract.getSelectedRow();
         int ret = theSetupControl.deleteContract(theContract,row);
         if(ret == 0)
         {
             return;
         }
         clearDataAll();
         setEnableGroup(false);
         setEnableDataGroup(false);
         searchContract();
    }//GEN-LAST:event_jButtonDelActionPerformed
    private void jButtonDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDel1ActionPerformed
       deleteContractAdjust();
    }//GEN-LAST:event_jButtonDel1ActionPerformed
    private void jButtonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd1ActionPerformed
        setEnableDataGroup(true);
        setClearData();
        theContractAdjust = new ContractAdjust();
    }//GEN-LAST:event_jButtonAdd1ActionPerformed
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        setEnableGroup(true);
        clearDataAll();
        theContract = new Contract();
        this.jTextFieldCode.requestFocus();
    }//GEN-LAST:event_jButtonAddActionPerformed
    private void jTableGroupContractMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGroupContractMouseReleased
        selectGroupContract();      
    }//GEN-LAST:event_jTableGroupContractMouseReleased
    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        searchContract();
    }//GEN-LAST:event_jButtonSearchActionPerformed
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    public void searchContract()
   {   
       next = 0;
       prev = 0;
       String search = jTextFieldKeyword.getText();
       gContract =  theSetupControl.listContractGroupByNameId(search);
       setTableContractGroup(gContract,1);
    }
    public void cancelinsertGroupContract()
    {
        setEnableGroup(false);
        selectGroupContract();
        jTableGroupContract.requestFocus();
    }
  public void clearDataAll()
  {
       save=1;
       jTextFieldCode.setText("");
       jTextFieldName.setText("");
      this.updateOGContractAdjustV(null);
  }
  public void setClearData()
  {
      jTextFieldContract.setText("");
      jCheckBoxDraw.setSelected(false);
  }
   public void setEnableGroup(boolean var)
   {
       jTextFieldCode.setEditable(var);
       jTextFieldName.setEditable(var);
       jButtonSave.setEnabled(var);
   }
   public void setEnableDataGroup(boolean var)
   {
       jComboBoxCategory.setEnabled(var);
       jTextFieldContract.setEditable(var);
       jButtonSave.setEnabled(var);
       jCheckBoxDraw.setEnabled(var);
   }
    public void actionGroup()
    {
       ComboboxModel.initComboBox(jComboBoxCategory,theLookupControl.listCategoryGroupItem());
    }
    public void selectGroupContract()
    {
        selectFromTable();
        updateOGContract();
        setEnableGroup(true);
    }
    public void selectFromTable()
    {
        int row = jTableGroupContract.getSelectedRow();
        if(row==-1) return;
        String of = (String)jTableGroupContract.getValueAt(row, 0);
        Contract cot = new Contract();
        for(int i =0 ; i< gContract.size() ; i++)
        {           
             if(of == ((Contract)gContract.get(i)).contract_id)
                cot = (Contract)gContract.get(i);
        } 
        theContract = cot;
    }
    public void updateOGContract()
    {
        jTextFieldCode.setText(theContract.contract_id);
        jTextFieldName.setText(theContract.description);
        cData = theSetupControl.listContractAdjust(theContract.getObjectId());
        updateOGContractAdjustV(cData);
    }
    public void saveGroup()
    {
        theContract.contract_id = jTextFieldCode.getText();
        theContract.description = jTextFieldName.getText();
        theContract.method = "1";
        theSetupControl.saveContract(theContract);
        updateOGContract();
        searchContract();
  }
  public void saveContractAdjust()
  {
        int[] rows = this.jTableContractData.getSelectedRows();
        if(rows.length==1)
        {
            if(theContractAdjust==null)
                theContractAdjust = new ContractAdjust();
            theContractAdjust.adjustment = Gutil.getGuiData(jTextFieldContract);
            theContractAdjust.covered_id = Gutil.getGuiData(jComboBoxCategory);
            theContractAdjust.contract_id = theContract.getObjectId();
            if(jCheckBoxDraw.isSelected())
                    theContractAdjust.draw = "1";
            else    theContractAdjust.draw = "0";

            if(theSetupControl.saveContractAdjust(theContractAdjust)>0) 
                selectGroupContract();
        }
        else{
            String price = Gutil.getGuiData(jTextFieldContract);
            if(theSetupControl.saveContractAdjust(cData,rows,price)>0) 
                selectGroupContract();
        }
  }
    public void selectContractData()
    {
        int[] rows = jTableContractData.getSelectedRows();
        if(rows.length==1)
        {
            int row = jTableContractData.getSelectedRow();
            theContractAdjust = (ContractAdjust)cData.get(row);
            ComboboxModel.setCodeComboBox(jComboBoxCategory,theContractAdjust.covered_id);
            jTextFieldContract.setText((String)jTableContractData.getValueAt(row, 1));
            if(theContractAdjust.draw.equals("1"))
                jCheckBoxDraw.setSelected(true);
            else
                jCheckBoxDraw.setSelected(false);
            setEnableDataGroup(true);
        }
        else{
            setEnableDataGroup(true);
            jComboBoxCategory.setEnabled(false);
            jCheckBoxDraw.setEnabled(false);
            jTextFieldContract.setText("");
        }
    }
     public void deleteContractAdjust()
    {   
        int[]  row = jTableContractData.getSelectedRows();
        int ret = theSetupControl.deleteContractAdjust(cData,row);
        if(ret == 0)
        {
            return;
        }
        selectGroupContract();
    }
    public void updateOGContractAdjustV(Vector v)
    {
        cData = v;
        if(cData==null)
            cData = new Vector();
       TaBleModel tm = new TaBleModel(column,cData.size());
       for(int i=0;i<cData.size();i++)
       {
            ContractAdjust cd = (ContractAdjust)cData.get(i);
            if(!cd.covered_id.equals("null"))
            {
                CategoryGroupItem cgi = (CategoryGroupItem)theLookupControl
                    .readCategoryGroupItemById(cd.covered_id);
                try{  
                    tm.setValueAt(cgi.description,i,0);
                    tm.setValueAt(cd.adjustment,i, 1);
                }
                catch(Exception ex)
                {
                    tm.setValueAt("",i,0);
                    tm.setValueAt("",i, 1);
                }
            }
       }
       jTableContractData.setModel(tm);
       jTableContractData.getColumnModel().getColumn(0).setPreferredWidth(500);
       jTableContractData.getColumnModel().getColumn(1).setPreferredWidth(100);
       jTableContractData.getColumnModel().getColumn(1).setCellRenderer(TableRenderer.getRendererRight());
    } 
      public void setTableContractGroup(Vector voffice,int off)
    {
        //if(gContract==null)   
          //  gContract = new Vector();
        if(voffice == null)
        {
            TaBleModel tm = new TaBleModel(col,0);
            jTableGroupContract.setModel(tm);
            return;
        }
        Contract ct= new Contract();
        int count = offset;
        int p =0;
        int n =0;
        int c =0;
        if(voffice != null)
        {
            if(off == 1)
            {   p = prev;
                n = next;            
                prev = next;
                next = next + offset;
                if(next >= gContract.size())
                {   next = gContract.size();
                    count = next - prev;
                }
                if(count == 0)
                {   prev = p;
                    next = n;
                    count = n - p;
                }
            }
            else
            {   next = prev;
                prev = prev - offset;
                if(prev <=0)
                {    prev = 0;
                    next = offset;
                }
                if(next >= gContract.size())
                {   next= gContract.size();
                    count = next;
                }
            }
        }
       TaBleModel tm = new TaBleModel(col,count);
       for(int i=0;i<count;i++)
       {
           ct = (Contract)voffice.get(i+prev);   

           tm.setValueAt(ct.contract_id,i,0);
           tm.setValueAt(ct.description, i, 1);        
       }
       jTableGroupContract.setModel(tm);
       jTableGroupContract.getColumnModel().getColumn(0).setPreferredWidth(100);
       jTableGroupContract.getColumnModel().getColumn(1).setPreferredWidth(400);
    } 
  
    public void notifysetEnableForLift(boolean b) {
        jButtonDel.setVisible(b);
    }
    public int editOption(Option option) {
        Constant.println("PanelSetupContract function is not use.");
        return -1;
    }
    public Vector listOptionAll() {
        Constant.println("PanelSetupContract function is not use.");
        return null;
    }
    public void reFrashPanel() {
    }
    public Option readOption() {
        Constant.println("PanelSetupContract function is not use.");
        return null;
    }
    public int saveOption(Option option) {
        Constant.println("PanelSetupContract function is not use.");
        return -1;
    }
    public void setEnableForLift(boolean b) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hospital_os.gui.font.DefaultFont defaultFont1;
    private com.hospital_os.gui.font.FontFormatTitle fontFormatTitle1;
    protected javax.swing.JButton jButtonAdd;
    protected javax.swing.JButton jButtonAdd1;
    protected javax.swing.JButton jButtonDel;
    protected javax.swing.JButton jButtonDel1;
    protected javax.swing.JButton jButtonNext;
    protected javax.swing.JButton jButtonPrev;
    protected javax.swing.JButton jButtonSave;
    protected javax.swing.JButton jButtonSave1;
    protected javax.swing.JButton jButtonSearch;
    private javax.swing.JCheckBox jCheckBoxDraw;
    private javax.swing.JComboBox jComboBoxCategory;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelICD9code;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    protected javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.hosv3.gui.component.HJTableSort jTableContractData;
    protected com.hosv3.gui.component.HJTableSort jTableGroupContract;
    protected javax.swing.JTextField jTextFieldCode;
    private com.hospital_os.utility.DoubleTextField jTextFieldContract;
    protected javax.swing.JTextField jTextFieldKeyword;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
