/*
 * PanelSDSetupOfficeInCup.java
 *
 * Created on April 2, 2009, 10:40 AM
 */

package com.hosv3.gui.panel.detail;

import com.hospital_os.object.Office;
import com.hospital_os.usecase.connection.Persistent;
import com.hospital_os.utility.ComboboxModel;
import com.hosv3.utility.Constant;
import com.hospital_os.utility.Gutil;
import com.hosv3.control.HosControl;
import com.hosv3.control.LookupControl;
import com.hosv3.control.SetupControl;
import com.hosv3.gui.component.PanelSetupImp;
import com.hosv3.gui.dialog.HosDialog;
import com.hosv3.object.OfficeInCup;
import com.hosv3.utility.GuiLang;
import com.hosv3.utility.connection.UpdateStatus;
import java.util.Vector;

/**
 *
 * @author  Administrator
 */
public class PanelSDOfficeInCup extends javax.swing.JPanel  implements PanelSetupImp{
     final private int offset = 24;
    private int next =0;
    private int prev = 0;
    private int save = 0;
    private Office theOffice;
    String[] col = {"รหัส","ชื่อ"};
    
    /**
     เรียกใช้ control ที่ชื่อว่า lookupControl เพื่อทำการ set ค่า ให้กับ combobox ต่างๆ
     จะประกอบด้วย จังหวัด อำเภอ และ ตำบล 
     และเรียกใช้ SetupControl เพื่อทำการ ดิงข้อมูลของ office ขึ้นมาแสดง
     
     โดยทุกตัวจะเก็บข้อมูลไว้ใน vector ทั้งหมด
     
     */
    LookupControl theLookupControl;
    UpdateStatus theUS;
    SetupControl theSetupControl;
    ComboboxModel theComboboxModel;
    HosDialog theHD;
    Vector comboboxoffice = new Vector();
    Vector comboboxaddresscgw = new Vector();
    Vector comboboxaddressamp = new Vector();
    Vector comboboxaddresstmb = new Vector();
    private Vector theOfficeInCupV = new Vector();
    
   // public Office  theOffice;
    public PanelSDOfficeInCup(HosControl hc, UpdateStatus us,HosDialog hd) {
        this();
        setControl(hc,us);
        theHD = hd;
        //jTable1.setGuiMode(true);
    }
    public PanelSDOfficeInCup() {
        initComponents();
        setLanguage();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        defaultFont1 = new com.hospital_os.gui.font.DefaultFont();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldOffName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxChangwat = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFullName = new javax.swing.JTextArea();
        jComboBoxAmphur = new javax.swing.JComboBox();
        jComboBoxTambon = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDepartment = new javax.swing.JTextField();
        jTextFieldMoo = new javax.swing.JTextField();
        jTextFieldBed = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(300, 330));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 330));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 330));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(defaultFont1);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/hosv3/property/thai"); // NOI18N
        jLabel1.setText(bundle.getString("CODE")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(defaultFont1);
        jLabel2.setText(bundle.getString("OFFICE_OFFNAME")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        jTextFieldCode.setFont(defaultFont1);
        jTextFieldCode.setEnabled(false);
        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jTextFieldCode, gridBagConstraints);

        jTextFieldOffName.setFont(defaultFont1);
        jTextFieldOffName.setDoubleBuffered(true);
        jTextFieldOffName.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jTextFieldOffName, gridBagConstraints);

        jLabel3.setFont(defaultFont1);
        jLabel3.setText(bundle.getString("OFFICE_FULLNAME")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel3, gridBagConstraints);

        jComboBoxChangwat.setFont(defaultFont1);
        jComboBoxChangwat.setEnabled(false);
        jComboBoxChangwat.setMaximumSize(new java.awt.Dimension(150, 24));
        jComboBoxChangwat.setMinimumSize(new java.awt.Dimension(150, 24));
        jComboBoxChangwat.setPreferredSize(new java.awt.Dimension(150, 24));
        jComboBoxChangwat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChangwatActionPerformed(evt);
            }
        });
        jComboBoxChangwat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxChangwatFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jComboBoxChangwat, gridBagConstraints);

        jLabel5.setFont(defaultFont1);
        jLabel5.setText(bundle.getString("ADDRESS_CHANGWAT_COL")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(defaultFont1);
        jLabel6.setText(bundle.getString("ADDRESS_AMPHUR_COL")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel6, gridBagConstraints);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(150, 48));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(150, 48));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(150, 48));

        jTextAreaFullName.setFont(defaultFont1);
        jTextAreaFullName.setLineWrap(true);
        jTextAreaFullName.setWrapStyleWord(true);
        jTextAreaFullName.setDoubleBuffered(true);
        jTextAreaFullName.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaFullName);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        jComboBoxAmphur.setFont(defaultFont1);
        jComboBoxAmphur.setEnabled(false);
        jComboBoxAmphur.setMaximumSize(new java.awt.Dimension(150, 24));
        jComboBoxAmphur.setMinimumSize(new java.awt.Dimension(150, 24));
        jComboBoxAmphur.setPreferredSize(new java.awt.Dimension(150, 24));
        jComboBoxAmphur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAmphurActionPerformed(evt);
            }
        });
        jComboBoxAmphur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxAmphurFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jComboBoxAmphur, gridBagConstraints);

        jComboBoxTambon.setFont(defaultFont1);
        jComboBoxTambon.setEnabled(false);
        jComboBoxTambon.setMaximumSize(new java.awt.Dimension(150, 24));
        jComboBoxTambon.setMinimumSize(new java.awt.Dimension(150, 24));
        jComboBoxTambon.setPreferredSize(new java.awt.Dimension(150, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jComboBoxTambon, gridBagConstraints);

        jLabel7.setFont(defaultFont1);
        jLabel7.setText("ตำบล");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(defaultFont1);
        jLabel8.setText("สังกัด");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(defaultFont1);
        jLabel9.setText("หมู่ที่");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(defaultFont1);
        jLabel10.setText("เตียง");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel10, gridBagConstraints);

        jTextFieldDepartment.setFont(defaultFont1);
        jTextFieldDepartment.setDoubleBuffered(true);
        jTextFieldDepartment.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jTextFieldDepartment, gridBagConstraints);

        jTextFieldMoo.setFont(defaultFont1);
        jTextFieldMoo.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jTextFieldMoo, gridBagConstraints);

        jTextFieldBed.setFont(defaultFont1);
        jTextFieldBed.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel2.add(jTextFieldBed, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeActionPerformed
        //        theLookupControl.readHospitalByCode(this.jTextFieldCode.getText());
    }//GEN-LAST:event_jTextFieldCodeActionPerformed

    private void jComboBoxChangwatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChangwatActionPerformed
        // Add your handling code here:
        selectChangwat();
    }//GEN-LAST:event_jComboBoxChangwatActionPerformed

    private void jComboBoxChangwatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxChangwatFocusLost
        // Add your handling code here:
    }//GEN-LAST:event_jComboBoxChangwatFocusLost

    private void jComboBoxAmphurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAmphurActionPerformed
        // Add your handling code here:
        selectAmpor();
    }//GEN-LAST:event_jComboBoxAmphurActionPerformed

    private void jComboBoxAmphurFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxAmphurFocusLost
        // Add your handling code here:
        //selectAmpor();
    }//GEN-LAST:event_jComboBoxAmphurFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hospital_os.gui.font.DefaultFont defaultFont1;
    private javax.swing.JComboBox jComboBoxAmphur;
    private javax.swing.JComboBox jComboBoxChangwat;
    private javax.swing.JComboBox jComboBoxTambon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaFullName;
    private javax.swing.JTextField jTextFieldBed;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldDepartment;
    private javax.swing.JTextField jTextFieldMoo;
    private javax.swing.JTextField jTextFieldOffName;
    // End of variables declaration//GEN-END:variables
 private void setLookup()
    {   
        comboboxaddresscgw = theLookupControl.listAddressCGW();
        ComboboxModel.initComboBox(jComboBoxChangwat,comboboxaddresscgw);
        comboboxaddressamp = theLookupControl.listAddressAmp(ComboboxModel.getCodeComboBox(jComboBoxChangwat));
        ComboboxModel.initComboBox(jComboBoxAmphur,comboboxaddressamp);
        comboboxaddresstmb = theLookupControl.listAddressTmp(ComboboxModel.getCodeComboBox(jComboBoxChangwat),ComboboxModel.getCodeComboBox(jComboBoxAmphur));
        if(comboboxaddresstmb != null)
            ComboboxModel.initComboBox(jComboBoxTambon,comboboxaddresstmb);
    }
    /////////////////////Use this for decrease memory usage    
    /**
        นำค่าที่ได้จากการ query ของ ข้อมูลจังหวัด มาเก็บไว้ใน vector จากนั้นทำการ setค่าให้กับ combobox
     โดยเรียก class ที่ชื่อว่า ComboboxModel 
        จากนั้นก็ทำการ query ข้อมูลอำเภอ และตำบล
     
     */
    private void selectcomboCgw()
    {   comboboxaddresscgw = theLookupControl.listAddressCGW();
        ComboboxModel.initComboBox(jComboBoxChangwat,comboboxaddresscgw);
        comboboxaddressamp = theLookupControl.listAddressAmp(ComboboxModel.getCodeComboBox(jComboBoxChangwat));
        ComboboxModel.initComboBox(jComboBoxAmphur,comboboxaddressamp);
        comboboxaddresstmb = theLookupControl.listAddressTmp(ComboboxModel.getCodeComboBox(jComboBoxChangwat),ComboboxModel.getCodeComboBox(jComboBoxAmphur));
        if(comboboxaddresstmb != null)
            ComboboxModel.initComboBox(jComboBoxTambon,comboboxaddresstmb);
    }
    
    private void selectChangwat()
    {
        jComboBoxAmphur.removeAllItems();
        comboboxaddressamp.clear();
        comboboxaddressamp = theLookupControl.listAddressAmp(ComboboxModel.getCodeComboBox(jComboBoxChangwat));
        if(comboboxaddressamp != null)
            ComboboxModel.initComboBox(jComboBoxAmphur,comboboxaddressamp);
    }
    private void selectAmpor()
    {  
        jComboBoxTambon.removeAllItems();
        if(jComboBoxChangwat !=null)
        {   comboboxaddresstmb = theLookupControl.listAddressTmp(null,ComboboxModel.getCodeComboBox(jComboBoxAmphur));
            if(comboboxaddresstmb != null)
                ComboboxModel.initComboBox(jComboBoxTambon,comboboxaddresstmb);
        }
    }
    
    public void clearAll() {
        // this.jTable1.clearSelection();
        Office office = new Office();
        office.setObjectId("");
        if(theHD.showDialogOffice(office))
        {
            office = theLookupControl.readHospitalByCode(office.getObjectId());
            this.setTheOffice(office);
        }
    }

    public Persistent getXPer() {
        return this.getTheOffice();
    }

    public void setXPer(Persistent x) {
        OfficeInCup oic = (OfficeInCup)x;
        Office  office = theLookupControl.readHospitalByCode(oic.code);
        this.setTheOffice(office);
    }

    public void setLanguage() {
        GuiLang.setLanguage(jLabel3);
        GuiLang.setLanguage(jLabel1);        
        GuiLang.setLanguage(jLabel2);
        GuiLang.setLanguage(jLabel3);
        GuiLang.setLanguage(jLabel8);        
        GuiLang.setLanguage(jLabel10);
        GuiLang.setLanguage(jLabel9);
        GuiLang.setLanguage(jLabel5);        
        GuiLang.setLanguage(jLabel6);
        GuiLang.setLanguage(jLabel7);   
        GuiLang.setLanguage(col);
    }

    public void setControl(HosControl hc, UpdateStatus us) {
        theUS = us;
        setEnabled(false);
        theLookupControl = hc.theLookupControl;
        theSetupControl = hc.theSetupControl;
        
        hc.theHS.theSetupSubject.addpanelrefrash(this);
        hc.theHS.theSetupSubject.addForLiftAttach(this);
        setLookup();
        jTextFieldCode.setEditable(false);
//        jTextFieldCode.setEnabled(false);
    }

    public void setupLookup() {
         selectcomboCgw();
    }
    
    public void setEnabled(boolean var)
    {
//        jTextFieldCode.setEnabled(var);
//        jTextAreaFullName.setEnabled(var);
//        jTextFieldBed.setEnabled(var);
//        jTextFieldDepartment.setEnabled(var);
//        jTextFieldMoo.setEnabled(var);
//        jTextFieldOffName.setEnabled(var);
//        jComboBoxAmphur.setEnabled(var);
//        jComboBoxChangwat.setEnabled(var);
//        jComboBoxTambon.setEnabled(var);
      
    }

   public boolean deleteXPer(Persistent x) {
        return (this.theSetupControl.deleteOfficeInCup((Office)x)>0);
    }

    public boolean saveXPer(Persistent x) {
       //return false;
      return (this.theSetupControl.saveOfficeInCup((Office)x)>0);
    }

    public Vector listXPer(String key, String active, int offset) {
        return theLookupControl.listOfficeInCup(key);
    }

    public boolean isActiveVisible() {
        return false;
    }

    public static String TITLE = Constant.getTextBundle("สถานพยาบาลในเขต");
    public String getTitle() {
        return TITLE;
    }

    public Office getTheOffice() {
         if(theOffice==null)
       {
            theOffice = new Office();
            theOffice.minis = "";
            theOffice.dep = "";
            theOffice.off_type = "";
            theOffice.specific = "";
       }
        theOffice.pk_field = jTextFieldCode.getText();
        theOffice.name = jTextFieldOffName.getText();
        theOffice.off_name1 = jTextAreaFullName.getText();
        theOffice.off_name2 = jTextFieldDepartment.getText();
        theOffice.bed = jTextFieldBed.getText();
        theOffice.moo = jTextFieldMoo.getText();
        if((Gutil.getGuiData(jComboBoxChangwat)==null)||(Gutil.getGuiData(jComboBoxChangwat).equals("")))
        {  
        theOffice.changwat="00";
        }
        else
        {
         theOffice.changwat = Gutil.getGuiData(jComboBoxChangwat).substring(0,2);
        }
        if((Gutil.getGuiData(jComboBoxAmphur)== null)||(Gutil.getGuiData(jComboBoxAmphur).equals("")))
        {
          theOffice.ampur ="00";
        }
        else
        {
            theOffice.ampur = Gutil.getGuiData(jComboBoxAmphur).substring(2,4);
        }
        if((Gutil.getGuiData(jComboBoxTambon)==null)||(Gutil.getGuiData(jComboBoxTambon).equals("")))
        {   
         theOffice.tambon = "00";
        }
        else
        {
            theOffice.tambon = Gutil.getGuiData(jComboBoxTambon).substring(4,6);
        }
        return theOffice;
    }

    public void setTheOffice(Office office) {
       
        theOffice = office;
        jTextFieldCode.setText(office.getObjectId());
//        jTextFieldCode.setEditable(false);
        jTextFieldOffName.setText(office.name);
        jTextAreaFullName.setText(office.off_name1);
        jTextFieldDepartment.setText(office.off_name2);
        jTextFieldBed.setText(office.bed);
        jTextFieldMoo.setText(office.moo);
        ComboboxModel.setCodeComboBox(jComboBoxChangwat, office.changwat+"0000");
        if(office.changwat != null)
        if(!ComboboxModel.setCodeComboBox(jComboBoxAmphur, office.changwat+office.ampur+"00"))
        {
            jComboBoxAmphur.removeAllItems();
            comboboxaddressamp.clear();
        }
        selectAmpor();
        //ComboboxModel.setCodeComboBox(jComboBoxTambon, office.changwat+office.ampur+office.tambon);
        if(office.tambon !=null)
        if(!ComboboxModel.setCodeComboBox(jComboBoxTambon, office.changwat+office.ampur+office.tambon))
        {   
            jComboBoxTambon.removeAllItems();
            comboboxaddresstmb.clear();
        } 
        setEnabled(true);
    }

    public Vector getTheOfficeInCupV() {
        return theOfficeInCupV;
    }

    public void setTheOfficeInCupV(Vector item) {
        theOfficeInCupV = item;
  
    }

    public boolean isStartVisible() {
        return false;
    }
        

}
