/*
 * PanelReportQuery.java
 *
 * Created on 6 กันยายน 2548, 11:15 น.
 */

package com.reportquery.gui.panel;

import com.hosv3.utility.connection.UpdateStatus;
import com.reportquery.manage.HosManage;
import com.reportquery.usecase.gui.*;
import com.reportquery.utility.Config;
import com.reportquery.utility.Language;
import com.reportquery.help.ShowHelpReportQuery;
import com.reportquery.utility.Language;
import com.hospital_os.object.MenuItemPlugIn;
import com.hospital_os.object.Version;


import java.util.Vector;

/**
 *
 * @author  tong(Padungrat)
 */
public class PanelReportQuery extends javax.swing.JPanel implements 
 GUIManage,StandardGUI
{
    
    /** Creates new form PanelReportQuery */
    PanelPeportSqlParam thePanelPeportSqlParam;
    PanelSetupSQLTemplate thePanelSetupSQLTemplate;
    
    HosManage theManager;
    UpdateStatus theUS;
    ShowHelpReportQuery theShowHelpReportQuery;
    int language = 1;
    
    public PanelReportQuery(HosManage manager,UpdateStatus us) {
        theManager = manager;
        theUS = us;
        theManager.theManageControl.theManageSubject.theGUISubject.registerGUIManage(this);
        initComponents();
        addTab();
    }
    public PanelReportQuery() {
        initComponents();
    }
    public void setControl(HosManage manager,UpdateStatus us) {
        theManager = manager;
        theUS = us;
        theManager.theManageControl.theManageSubject.theGUISubject.registerGUIManage(this);
        addTab();
    }
    private void addTab()
    {
        thePanelSetupSQLTemplate = new PanelSetupSQLTemplate(theManager);
        thePanelPeportSqlParam = new PanelPeportSqlParam(theManager,theUS);
        //Query รายงาน
        addTabReportQuery(Language.getTextBundle("QueryReport", language), thePanelPeportSqlParam);
        //แก้ไข รายงานSQL
        addTabReportQuery(Language.getTextBundle("editSQL", language), thePanelSetupSQLTemplate);
    }
     /**ใช้ในการกำหนด version ของ การออกรายงาน 12 แฟ้ม 
     *@return เป็น Object ของ Vesion
     */
    public Version getVersion()
    {
        Version version = new Version();
        version.app_code = Config.getTextBundle("Version");
        version.description = Config.getTextBundle("Description");
        version.update_time = Config.getTextBundle("Update");
        version.db_code = Config.getTextBundle("VersionDatabaseUse");
        
        return version;
        
    }   
    
    /**ใช้ในการ ส่ง Dialog Help ให้กับ Frame หลัก*/
    public Vector getMenuItem()
    {   javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        theShowHelpReportQuery = new ShowHelpReportQuery();
        
        jMenuItem1.setText(Language.getTextBundle("ReportQueryHelp",language));
        theShowHelpReportQuery.addID(jMenuItem1);
        
        MenuItemPlugIn theMenuItemPlugIn = new MenuItemPlugIn();
        theMenuItemPlugIn.authen = true;
        theMenuItemPlugIn.theJMenuItem = jMenuItem1;
                
        Vector vc = new Vector();
        
        
        vc.add(theMenuItemPlugIn);
        return vc;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneShowReport = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jTabbedPaneShowReport, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    /**ใช้ในการ เพิ่ม tab ที่ต้องการจะให้แสดงผลข้อมูล
     * @param nameTab เป็น String ของชื่อ tab ที่ต้องการจะให้แสดง
     * @param panel เป็น JPanel ของ panel ที่ต้องการจะเพิ่มลง tab
     */
    public void addTabReportQuery(String nameTab,javax.swing.JPanel panel)
    {
        jTabbedPaneShowReport.addTab(nameTab, panel);
    }

    /**ใช้ในการแสดง panel SetupSQLTemplate */
    private void showPanelSetupSQLTemplateSelected()
    {
        int size = this.jTabbedPaneShowReport.getComponentCount();
        int sizeMch =0;
        System.out.println("Size Is : " + size);
        for(int i =0; i<  size ; i++)
        {
            if(this.jTabbedPaneShowReport.getComponentAt(i).equals(thePanelSetupSQLTemplate))
            {
                
                this.jTabbedPaneShowReport.setSelectedIndex(i);
            }
        }
    }
    
    
    public void notifyCallShowSetupSQLTemplate() {
        System.out.println("notifyCallShowSetupSQLTemplate");
        showPanelSetupSQLTemplateSelected();
    }

    public void notifyRefreshGUI() {
    }

    public void setLanguage() {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPaneShowReport;
    // End of variables declaration//GEN-END:variables
    
}
