/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelResultRp.java
 *
 * Created on 2 ¸.¤. 2552, 17:21:41
 */

package com.reportcenter.gui.dialog;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author henbe
 */
public class DialogResultRp extends javax.swing.JDialog {

    /** Creates new form PanelResultRp */
    public DialogResultRp(JFrame jf,boolean modal) {
        super(jf,modal);
        initComponents();
        this.setSize(450,450); 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenSize.width-this.getSize().width)/2, (screenSize.height-this.getSize().height)/2);
    }
    public static void showResult(JFrame jf,String str){
        DialogResultRp dd = new DialogResultRp(jf,true);
        dd.jLabel1.setText(str);
        dd.setVisible(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(253, 250, 247));
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        DialogResultRp.showResult(null,"<html><body><br>a<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>a<br><br>a<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>a<br></body></html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
