/*
 * DialogException.java
 *
 * Created on 20 มกราคม 2549, 13:45 น.
 */

package com.hosv3.utility;

import java.io.PrintStream;
import java.awt.*;
import javax.swing.*;

/**
 * @deprecated ย้ายไปอยู่ใน control.gui
 * @author  henbe
 */
public class DialogException extends javax.swing.JDialog {
    
	
    PrintStream ps;
    /** Creates new form DialogException */
    public DialogException(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        String henbe_deprecate;
        initComponents();
        this.setSize(600, 200);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screenSize.width-getSize().width)/2, (screenSize.height-getSize().height)/2);
    }
    public PrintStream getPrintStream(){
        if(ps==null){
            HOutputStream hos = new HOutputStream();
            hos.setTextArea(this.jTextArea1);
            ps = new PrintStream(hos);
        }
        return ps;
    }
    public static void showException(String title,Exception e,JFrame jf){
        DialogException de = new DialogException(jf, true);
        e.printStackTrace(de.getPrintStream());
        de.setTitle(title);
        de.setVisible(true);
    }
    public static void showException(Exception e){
        showException("Show Exception Error",e,null);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        try{
            Integer.parseInt("aa");
        }
        catch(Exception e){
            DialogException.showException(e);
        }
        try{
            Integer.parseInt("bb");
        }
        catch(Exception e){
            DialogException.showException(e);
        }
     }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
